### ISSUE TITLE
Fullscreen switch doesn't work.

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/xenko#132]
Alt-Enter initiates the switch to fullscreen, but the application just returns to the original size after black. I assume that the engine will handle fullscreen switch, is that a correct assumption?

**Comment by FuzsyDk** [comment]
I have experienced the same issue. Is there another way to make the application go fullscreen?

**Comment by sinkingsugar** [comment]
This should be fixed now.
