### ISSUE TITLE
Pre-requisites not installed properly

### ISSUE THREAD

**Issue by suboxygen** [SiliconStudio/xenko#143]
Upon installation I left only one of the packages checked to installed for the prerequisite. Now I cannot seem to start the demo projects even because files are missing. I un-installed, then re-installed and the option to install those prerequisites is missing now. It doesn't pop up as an option anymore. Kind of stuck in a loop now. What is the fix? Does someone have a list of the prerequisites put together that I can download and install then?

Thanks a lot!

- Noob josh.

**Comment by xen2** [comment]
You mean, the prerequisite screen doesn't show up at all? (probably because it considers all of them installed)

**Comment by Benlitz** [comment]
The prerequisite installation (as well as the installer) have been completely reworked. I'm closing this issue for now, feel free to re-open or create a new issue if you got a similar problem again
