### ISSUE TITLE
Cubemap Reflection Sample Error

### ISSUE THREAD

**Issue by Toasterthegamer** [SiliconStudio/xenko#148]
I can't seem to get the sample to run it throws an error on this line:

RenderSystem.Pipeline.Renderers.Add(lightDeferredProcessor);

I've got a intel HD 4000 in my work laptop which I suspect is the issue? The error is:

CubemapReflection.vshost.exe: Managed (v4.0.30319)' has exited with code -1073741819 (0xc0000005) 'Access violation'.

I'm going to test on my home PC which has a 760 in it as soon as I get that setup for development. I didn't have any problems with any of the other samples however.

**Comment by axefrog** [comment]
Just tested on my machine. I'm using an NVIDIA GTX 670, and it works for me.

**Comment by xoofx** [comment]
Intel GPU are often unreliable compare to NVidia, AMD. We haven't done any significant testing on this kind of GPU, but we will try to integrate them in our testing HW.
