### ISSUE TITLE
Test certificate is missing in WinRT (Windows store) apps.

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/xenko#150]
There are a few warnings that come up when creating a WinRT (Windows store) app. They can be resolved by 

1) deleting the certificate file that isn't found, it's under the WindowsStore project. 
2) generating a new test certificate - Double click on Package.appmanifest, Click 'Choose Certificate...', Open the Configure Certificate pulldown and Create test certificate...

I didn't bother using a password as I don't have much of an idea about what these certificates are used for. But this created a fresh certificate that removed the warnings.

**Comment by Benlitz** [comment]
Windows Store is not supported anymore by Xenko
