### ISSUE TITLE
Exception when running WinRT (WindowsStore) game - Unable to find compiled shader

### ISSUE THREAD

**Issue by Gavin-Williams** [SiliconStudio/xenko#151]
I am receiving an error when I run my WinRT app. I have dragged and dropped stuff over from another project straight into Visual Studio, including Effects. And everything compiles (and i've recompiled from game-studio as well for Windows, but WindowsStore won't compile). But when the app runs, I get an exception on the Game.Run() method (where all exceptions go unfortunately). The error is:

InvalidOperationException
Unable to find compiled shaders [**shaders_bytecode**/6be2e830282a26ece8033683515b903f]

Edit : I maybe accidentally duplicated an effect shader, and now I can't compile the project from GameStudio, giving the error..

[CSC(0,0)]: Error: Source file 'Effects\ComputeColorTextureIndexed1.cs' could not be found

Note the 1 on the end, a result of the duplication.

**Comment by Gavin-Williams** [comment]
Extra info: I rebuilt the project and I still get the message ..

Unable to find compiled shaders.

I have set the project type to Mixed and Windows Store x86 & x64. Although I want access to a WinRT component in C++. So I think it needs to stay on mixed.

**Comment by xen2** [comment]
Feel free to send us the project by email if you want us to take a closer look.

**Comment by Gavin-Williams** [comment]
Ok, thanks, I've sent a link to an archive of the solution.

**Comment by Discosultan** [comment]
I ran into similar issue where I'm unable to run WindowsStore projects. I'll provide a link to that repo in case it might provide helpful:

[The GitHub repo for my solution.](https://github.com/Discosultan/Paradox.Playground)
Box, Hills and Shapes projects all suffer from it.

I remember I tried a quick csproj and pdxpkg file comparison against a working solution but couldn't pin down anything of interest. Haven't investigated further.

**Comment by Discosultan** [comment]
Just for information, after beta09 the exception message is slightly more detailed:
<pre>
An exception of type 'System.InvalidOperationException' occurred in SiliconStudio.Paradox.Games.DLL but was not handled in user code

Additional information: Unable to find compiled shaders 
[__shaders_bytecode__/fbd69b593c03d9d0e65e3d83ea606198] for mixin 
[mixin TransformationWAndVP, VertexColorShading] with parameters 
[   CompilerParameters.DebugKey: True

   CompilerParameters.GraphicsPlatformKey: Direct3D11

   CompilerParameters.GraphicsProfileKey: Level_9_1]
</pre>

**Comment by Benlitz** [comment]
Windows Store is not supported anymore by Xenko

**Comment by Gavin-Williams** [comment]
So have you reverted to the legacy desktop model? And you now don't target the Window Runtime at all now, is that right?

**Comment by sinkingsugar** [comment]
UWP , Windows 10+ store is supported. 
WinRT, 8, 8.1 API level is not supported anymore

**Comment by Gavin-Williams** [comment]
Ok, thanks for the clarification. I would like to add that saying that it doesn't support WinRT isn't exactly correct then either, as WinRT is part of the UWP. WinRT = Windows Runtime.

I had a debate about this with someone online, and had to point out that WinRT still refers to the Windows Runtime today, as evidenced by the release of C++/WinRT in January 2017.

I think it's important that WinRT is used correctly, otherwise it gets confusing. Someone reading your comment might think that WinRT is dead, and that's just not the case.
