### ISSUE TITLE
Recast navigation

### ISSUE THREAD

**Issue by amerkoleci** [SiliconStudio/xenko#160]
Do you plan to add recast navigation into paradox? This willl invoke the necessity to create native pinvoke library and call the methods from c#

**Comment by boriscallens** [comment]
How about http://sharpnav.com/ ? Is straight up C#.
Not a lawyer, but I think the MIT license allows redistribution.

**Comment by Toasterthegamer** [comment]
sharpnav is great and you can integrate it into paradox probably fairly easily. You might need to port it over to PCL however which can be somewhat of a challenge depending on what they used.

**Comment by xenux** [comment]
Thanks for the proposition, we will consider it :)

**Comment by Kryptos-FR** [comment]
Navigation meshes using [Recast](https://github.com/recastnavigation/recastnavigation) have been added in 1.9-beta version.
