### ISSUE TITLE
Step-by-step tutorial

### ISSUE THREAD

**Issue by Borkason** [SiliconStudio/xenko#161]
From a complete newcomer point of view, I find it extremely difficult to get started with Paradox3D. Even the basic explanations require basic knowledge of the engine. I took some time to write down my idea of a '*Getting Started*' documentation.

While there are samples, those are not self-explanatory. My idea is to have the changes explained, that happen between each two of every steps. Of course, I hope to see a step-by-step guide similar to the following and I also hope my ideas are good and welcome! :)

**1. Create a new project from the 'New Game' template**
This should explain the "New Game" template, the constructor method with the ` GraphicsDeviceManager.PreferredGraphicsProfile = new[] { GraphicsProfile.Level_9_1 };` line, the `LoadContent()` method, the `CreatePipeline()` method with its four renderers, the `GameScript()` method and the `while (isRunning)` loop with the `Script.NextFrame()` method.

**2. Changing the resolution and adding a background**
This explains how to change the resolution and how to add a background image (fixed, stretched or repeated).

**3. Displaying assets**
This part explains how to create a sprite asset and how to change the code from part 2 in order to position and display the sprite in the game window. Then it shows how to do the same with a 3D model.

**4. Animating sprites or models**
Now here we could learn how to animate an object. First how to have an animated SpriteGroup consisting of a number of images, and how to animate a 3D model.

**5. Moving an object**
Show how to use keyboard input to move the object in a two-dimensional space: The spritegroup left/right/top/bottom and the 3D model north/east/south/west.

**6. Collisions**
Now that we can move the object, collisions could be explained. So have a starting point and a target area and display a text when the object moves into the target area.

**Comment by Gavin-Williams** [comment]
I suspect that the team would want to prioritize work on the engine, there's still a lot of work to do before it's ready for prime time. If the community could start producing tutorials or articles on various aspects of the engine and how to use it, that would be good. I feel the same way, that we need a lot more information. Or even consolidate the tid-bits that are around now and draft some usage documents.

**Comment by xoofx** [comment]
Thanks for your suggestion. We are definitely committed to improve the documentation, but due to resource development constraints and the fact that we want to push new features (like the Scene Editor, new material system...etc, scripting system...etc.), we haven't had the time to improve the documentation since the launch of Paradox last year in September. Also, we agree that many things today are not easy to use and we want to improve the API and workflow to make these things a lot more easier. We expect to settle a good part of this progressively by the end of the year.

**Comment by Benlitz** [comment]
Hi,
The getting started section of the documentation has been rewritten to include the latest features of Xenko, and we will keep improving the documentation continuously from now.
I'm closing this issue. Note that if you would like to contribute to the documentation you are welcome to submit pull requests on the [documentation repository](https://github.com/SiliconStudio/xenko-docs) or open issues there.
