### ISSUE TITLE
00-BuildParadox.bat is hard-coded to look for VS2012 path, environment variables

### ISSUE THREAD

**Issue by deranen** [SiliconStudio/xenko#177]
Building Paradox using the "00-BuildParadox.bat" batch file fails for me even though I have Visual Studio 2013 installed (a prerequisite according to https://github.com/SiliconStudio/paradox/blob/master/doc/GettingStarted.md).

The actual error message I get is the following:

*snip*\paradox\sources\tools\SiliconStudio.Paradox.VisualStudio.Package\SiliconStudio.Paradox.VisualStudio.Package.csproj(309,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\VSSDK\Microsoft.VsSDK.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The root of the problem is the following line in "00-BuildParadox.bat":
set VS_VCVARSALL=%ProgFiles86Root%\Microsoft Visual Studio 11.0\vc\vcvarsall.bat

My setup actually happens to have had VS2012 installed before, so the batch file finds this path. However, this leads to the build expecting to find the VS2012 SDK, which I don't have, and can't install since it requires VS2012.

I suggest that these batch files are updated to reflect the VS2013 requirement.

Regards,
-David

**Comment by gitfool** [comment]
I'd applied the exact same patch to my fork since I only use VS 2013; but now I build everything using the sln files anyway. Also, I think VS 2012 is still meant to be supported by Paradox? Maybe it will be dropped when VS 2015 is released?

**Comment by deranen** [comment]
The link in my original post really gives the impression that Visual Studio 2013 or later is required. If not, then I would suggest a change to GettingStarted.md. The batch file still needs work, though (PR: #178).

**Comment by xen2** [comment]
00-BuildParadox.bat is obsolete and should have been either removed of updated.
The official way of building from command line is with "Paradox.build" (there is targets such as BuildWindows, BuildAndroid, etc...).

**Comment by gitfool** [comment]
Ah, I missed that. I wondered why there were no batch files for Windows Phone and Windows Store targets. It would be good to clear that up - either remove them or fix them to use the VS 2013 tools.

**Comment by deranen** [comment]
OK - good! The batch files are clearly not needed, then. I will make a pull request for removing them possibly later today, or tomorrow evening, unless someone is quicker than me.

**Comment by deranen** [comment]
Now that I'm looking at the batch files, I'm not so sure which ones we should remove, modify, or keep. I suggest someone else take a stab at fixing this.

**Comment by xen2** [comment]
Those files have been removed, closing issue.
