### ISSUE TITLE
Asset View features

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#214]
Hi, could we have refresh button and tree view for Asset View in Paradox Studio? :)

**Comment by Benlitz** [comment]
Hi, could you detail a little bit what you mean by a refresh button and a tree view?
Note that there's already a treeview to visualize asset hierarchy (the "solution explorer")

**Comment by EmptyKeys** [comment]
ad refresh) Let's say you are working on game in team. You keep everything in some central repository (Perforce, Git, TFS whatever) and someone on your team adds new asset. You update your local sources, but you have to restart Paradox Studio to see that new asset. I didn't find any other way. From my experience I would suggest simple refresh button. Automatic processes are usually bugy for this.

ad Tree View) I know there is solution explorer tree view, but UI experience is not good enuf. :) I think that Unity engine project view is much more user friendly. So there are 2 ways, what you could do. Add new tree view to Asset view (you already have grid view there) or merge Solution explorer with Asset view somehow. I prefer to have tree view button in Asset View so I can see dictionaries etc. there.

**Comment by Benlitz** [comment]
About the refresh option: this is something we'll definitively add in the future. We haven't decided yet how we'll implement it (probably: detecting changes and display a message to ask the user whether to reload the project, a bit like Visual Studio does)

About the tree view: do you mean that the tree view should display both folders and assets? Unity does not seem to do that (it displays only folders). Or do you mean that you would like to see folders in the asset view (more like what I observe from unity)?

**Comment by EmptyKeys** [comment]
ad tree view) both folders and assets. You can switch to One Column Layout in Unity Project view so you can see everything in one tree.

**Comment by Benlitz** [comment]
Ok I see. We will consider this option

**Comment by Kryptos-FR** [comment]
Since version 1.5-beta (December release), folders can be displayed in the Asset View.

**Comment by EmptyKeys** [comment]
Cool, thanks guys
