### ISSUE TITLE
Reflecting Script entities within Paradox Editor

### ISSUE THREAD

**Issue by Joojooo** [SiliconStudio/xenko#219]
Hi Paradox team,

I've been playing a bit around Paradox and the engine looks great and promising!

I have an issue with script files: after updating a script (adding / removing an entity), the editor will not reflect the updated list of entities (in the script panel displayed under Logic component), and I could not find any ways to reload it within the editor (I have to close and restart the editor in order to see the change in the editor).

Please let me know if you have any solutions or fix

**Comment by xen2** [comment]
Hi, thanks for the feedback!
You are right that currently a close/load of the project is needed.
That's a known issue that will be addressed later (it requires some work under the hood to properly update assets to new assemblies on the fly).

**Comment by Kryptos-FR** [comment]
Assemblies can be reloaded without having to close and reload the project.
