### ISSUE TITLE
All projects does not launch on Lenovo MIIX 3-1030 device on windows store platform

### ISSUE THREAD

**Issue by codedraft** [SiliconStudio/xenko#265]
All projects(new game, and samples) without changes does not launch on this device. Target platform windows store. After deploy an application and run it - I saw only splashscreen. But on the simulator and on the local machine they worked.
System:
- windows 8.1
- DirectX 11

I think it is connected with troubles with windows store certification, because all projects did not pass a certification.

**Comment by Benlitz** [comment]
We added support for Universal Windows Platform and removed support for Windows Store / Phone.
