### ISSUE TITLE
Projects with skybox did not build on windows 8.1

### ISSUE THREAD

**Issue by codedraft** [SiliconStudio/xenko#266]
If I build new game with skybox element on windows platform, I have error:

[(0,0)]: Info: MyGame2.Game -> E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.Game.dll
[(0,0)]: Info: SiliconStudio AssemblyProcessor: "C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.1-beta\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5 --auto-notify-property --parameter-key --auto-module-initializer --serialization --serializationProjectReferencePaths="" "E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.Game.dll"
[(0,0)]: Info: "C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.1-beta\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5 --auto-notify-property --parameter-key --auto-module-initializer --serialization --serializationProjectReferencePaths="" "E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.Game.dll"
[(0,0)]: Info: Assembly has already been processed, skip it.
[(0,0)]: Info: Выполните переназначение app.config для сборки "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" из версии "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.dll] в версию "4.0.10.0" [] для разрешения конфликта и избежания предупреждения.
[C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(1819,5)]: Warning: Обнаружены конфликты между различными версиями одной и той же зависимой сборки. Установите свойство "AutoGenerateBindingRedirects" в файле проекте равным true. Дополнительные сведения см. по адресу http://go.microsoft.com/fwlink/?LinkId=294190.
[(0,0)]: Info: MyGame2.Windows -> E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.exe
[(0,0)]: Info: SiliconStudio AssemblyProcessor: "C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.1-beta\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5 --auto-notify-property --parameter-key --auto-module-initializer --serialization --serializationProjectReferencePaths="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.Game.dll" "E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.exe"
[(0,0)]: Info: "C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.1-beta\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5 --auto-notify-property --parameter-key --auto-module-initializer --serialization --serializationProjectReferencePaths="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.Game.dll" "E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\MyGame2.exe"
[(0,0)]: Info: Assembly has already been processed, skip it.
[(0,0)]: Info: "C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.1-beta\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerApp.exe"  --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\data" --build-path="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\MyGame2.Windows\..\obj\data" --package-file="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\MyGame2.Windows\..\MyGame2.pdxpkg" --log-pipe="net.pipe://localhost/SiliconStudio.Assets.Editor.ffe88fa1-797c-4a5e-b0c3-4f6311ddee5b"
[(0,0)]: Info: : info 0,033s: BuildEngine arguments: --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path=E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\data --build-path=E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\MyGame2.Windows\..\obj\data --package-file=E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\MyGame2.Windows\..\MyGame2.pdxpkg --log-pipe=net.pipe://localhost/SiliconStudio.Assets.Editor.ffe88fa1-797c-4a5e-b0c3-4f6311ddee5b
[(0,0)]: Info: : info 0,034s: Starting builder.
[(0,0)]: Info: : info 2,329s: Compiling package [C:/Program Files/Silicon Studio/Paradox/GamePackages/Paradox.1.2.1-beta/Paradox.pdxpkg]
[]: Info: Compiling package [C:/Program Files/Silicon Studio/Paradox/GamePackages/Paradox.1.2.1-beta/Paradox.pdxpkg]
[(0,0)]: Info: : info 2,348s: Compiling package [E:/MY/C#/Paradox3D/Games/MyGame2/MyGame2/MyGame2.pdxpkg]
[]: Info: Compiling package [E:/MY/C#/Paradox3D/Games/MyGame2/MyGame2/MyGame2.pdxpkg]
[(0,0)]: Info: AssemblyHash: info 2,583s: Assembly Hash [SiliconStudio.Assets] => [3b7bbb271e10c4a853b94ee9126a9a2f]
[AssemblyHash]: Info: Assembly Hash [SiliconStudio.Assets] => [3b7bbb271e10c4a853b94ee9126a9a2f]
[(0,0)]: Info: : info 2,741s: Compression successful [Skybox Texture] to (128x128,R16G16B16A16_Float)
[]: Info: Compression successful [Skybox Texture] to (128x128,R16G16B16A16_Float)
[(0,0)]: Info: AssemblyHash: info 2,763s: Assembly Hash [SiliconStudio.Paradox.Assets] => [751c659defe6341493afabf70703c883]
[AssemblyHash]: Info: Assembly Hash [SiliconStudio.Paradox.Assets] => [751c659defe6341493afabf70703c883]
[(0,0)]: Info: : info 2,856s: Compression successful [Skybox Texture__ForSkyboxCompilation__] to (128x128,R16G16B16A16_Float)
[]: Info: Compression successful [Skybox Texture__ForSkyboxCompilation__] to (128x128,R16G16B16A16_Float)
[EXEC(0,0)]: Error: Exception in command 41cab380-e7e9-4325-a668-9e40007c2bb3: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Параметр задан неверно.
[(0,0)]: Info: 
[]: Error: Exception in command 41cab380-e7e9-4325-a668-9e40007c2bb3: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Параметр задан неверно.

   в SharpDX.Result.CheckError()
   в SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
   в SharpDX.Direct3D11.Buffer..ctor(Device device, IntPtr dataPointer, BufferDescription description)
   в SiliconStudio.Paradox.Graphics.Buffer.InitializeFromImpl(BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer)
   в SiliconStudio.Paradox.Graphics.Buffer.New(GraphicsDevice device, BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.CreateBuffer(BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryResource[TResource,TKey](Dictionary`2 cache, TKey description, Func`3 creator, Func`2 getDefinition, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryBuffer(BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedBuffer(BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedTypedBuffer(Int32 count, PixelFormat viewFormat, Boolean isUnorderedAccess, GraphicsResourceUsage usage)
   в SiliconStudio.Paradox.Rendering.ComputeEffect.LambertianPrefiltering.LambertianPrefilteringSH.DrawCore(RenderContext context)
   в SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(RenderContext context, String name)
   в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(String name)
   в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context)
   в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext)
   в SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext)
   в SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__22.MoveNext()
[(0,0)]: Info:    в SharpDX.Result.CheckError()
[(0,0)]: Info:    в SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
[(0,0)]: Info:    в SharpDX.Direct3D11.Buffer..ctor(Device device, IntPtr dataPointer, BufferDescription description)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.Buffer.InitializeFromImpl(BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.Buffer.New(GraphicsDevice device, BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.CreateBuffer(BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryResource[TResource,TKey](Dictionary`2 cache, TKey description, Func`3 creator, Func`2 getDefinition, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryBuffer(BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedBuffer(BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedTypedBuffer(Int32 count, PixelFormat viewFormat, Boolean isUnorderedAccess, GraphicsResourceUsage usage)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.ComputeEffect.LambertianPrefiltering.LambertianPrefilteringSH.DrawCore(RenderContext context)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(RenderContext context, String name)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(String name)
[(0,0)]: Info:    в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context)
[(0,0)]: Info:    в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext)
[(0,0)]: Info:    в SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext)
[(0,0)]: Info:    в SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__22.MoveNext()
[E:/MY/C#/Paradox3D/Games/MyGame2/MyGame2/Assets/Shared/Skybox.pdxsky(1,1)]: Error: BuildStep 41cab380-e7e9-4325-a668-9e40007c2bb3 failed.
[E:/MY/C#/Paradox3D/Games/MyGame2/MyGame2/Assets/Shared/Skybox.pdxsky(1,1)]: Error: BuildStep 41cab380-e7e9-4325-a668-9e40007c2bb3 failed.
[EXEC(0,0)]: Error: Exception in command 41cab380-e7e9-4325-a668-9e40007c2bb3: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Параметр задан неверно.
[(0,0)]: Info: 
[(0,0)]: Info:    в SharpDX.Result.CheckError()
[(0,0)]: Info:    в SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
[(0,0)]: Info:    в SharpDX.Direct3D11.Buffer..ctor(Device device, IntPtr dataPointer, BufferDescription description)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.Buffer.InitializeFromImpl(BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.Buffer.New(GraphicsDevice device, BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.CreateBuffer(BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryResource[TResource,TKey](Dictionary`2 cache, TKey description, Func`3 creator, Func`2 getDefinition, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryBuffer(BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedBuffer(BufferDescription description, PixelFormat viewFormat)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedTypedBuffer(Int32 count, PixelFormat viewFormat, Boolean isUnorderedAccess, GraphicsResourceUsage usage)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.ComputeEffect.LambertianPrefiltering.LambertianPrefilteringSH.DrawCore(RenderContext context)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(RenderContext context, String name)
[(0,0)]: Info:    в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(String name)
[(0,0)]: Info:    в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context)
[(0,0)]: Info:    в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext)
[(0,0)]: Info:    в SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext)
[(0,0)]: Info:    в SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__22.MoveNext()
[]: Error: Exception in command 41cab380-e7e9-4325-a668-9e40007c2bb3: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Параметр задан неверно.

   в SharpDX.Result.CheckError()
   в SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
   в SharpDX.Direct3D11.Buffer..ctor(Device device, IntPtr dataPointer, BufferDescription description)
   в SiliconStudio.Paradox.Graphics.Buffer.InitializeFromImpl(BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer)
   в SiliconStudio.Paradox.Graphics.Buffer.New(GraphicsDevice device, BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.CreateBuffer(BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryResource[TResource,TKey](Dictionary`2 cache, TKey description, Func`3 creator, Func`2 getDefinition, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Graphics.GraphicsResourceAllocator.GetTemporaryBuffer(BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedBuffer(BufferDescription description, PixelFormat viewFormat)
   в SiliconStudio.Paradox.Rendering.RendererCoreBase.NewScopedTypedBuffer(Int32 count, PixelFormat viewFormat, Boolean isUnorderedAccess, GraphicsResourceUsage usage)
   в SiliconStudio.Paradox.Rendering.ComputeEffect.LambertianPrefiltering.LambertianPrefilteringSH.DrawCore(RenderContext context)
   в SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(RenderContext context, String name)
   в SiliconStudio.Paradox.Rendering.DrawEffect.Draw(String name)
   в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context)
   в SiliconStudio.Paradox.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext)
   в SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext)
   в SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__22.MoveNext()
[EXEC(0,0)]: Error: Asset [Skybox] failed to compile
[]: Error: Asset [Skybox] failed to compile
[E:/MY/C#/Paradox3D/Games/MyGame2/MyGame2/Assets/Shared/Skybox.pdxsky(1,1)]: Error: BuildStep Asset build steps [SkyboxAsset:'Skybox'] (3 items) failed.
[E:/MY/C#/Paradox3D/Games/MyGame2/MyGame2/Assets/Shared/Skybox.pdxsky(1,1)]: Error: BuildStep Asset build steps [SkyboxAsset:'Skybox'] (3 items) failed.
[EXEC(0,0)]: Error: BuildStep Build step list (287 items) failed.
[]: Error: BuildStep Build step list (287 items) failed.
[]: Error: BuildStep Build step list (1 items) failed.
[EXEC(0,0)]: Error: BuildStep Build step list (1 items) failed.
[(0,0)]: Info: : info 3,837s: 
[]: Info: 
[]: Error: Build finished in 572 steps. Command results: 0 succeeded, 568 up-to-date, 4 failed, 0 not triggered due to previous failure.
[EXEC(0,0)]: Error: Build finished in 572 steps. Command results: 0 succeeded, 568 up-to-date, 4 failed, 0 not triggered due to previous failure.
[EXEC(0,0)]: Error: Build failed.
[]: Error: Build failed.
[(0,0)]: Info: : info 3,890s: Generate bundles: Scan assets and their dependencies...
[]: Info: Generate bundles: Scan assets and their dependencies...
[(0,0)]: Info: : info 3,893s: Generate bundles: Assign assets to bundles...
[]: Info: Generate bundles: Assign assets to bundles...
[EXEC(0,0)]: Error: Unhandled exception: Could not find asset Skybox for bundle default
[(0,0)]: Info: System.InvalidOperationException: Could not find asset Skybox for bundle default
[(0,0)]: Info:    в SiliconStudio.Assets.CompilerApp.BundlePacker.CollectBundle(ResolvedBundle resolvedBundle, String assetUrl, IAssetIndexMap assetIndexMap)
[(0,0)]: Info:    в SiliconStudio.Assets.CompilerApp.BundlePacker.CollectBundle(ResolvedBundle resolvedBundle, String assetUrl, IAssetIndexMap assetIndexMap)
[(0,0)]: Info:    в SiliconStudio.Assets.CompilerApp.BundlePacker.Build(Logger logger, PackageSession packageSession, PackageProfile profile, String indexName, String outputDirectory, ISet`1 disableCompressionIds)
[(0,0)]: Info:    в SiliconStudio.Assets.CompilerApp.PackageBuilder.BuildMaster()
[(0,0)]: Info:    в SiliconStudio.Assets.CompilerApp.PackageBuilder.Build()
[(0,0)]: Info:    в SiliconStudio.Assets.CompilerApp.Program.Main(String[] args)
[]: Error: Unhandled exception: Could not find asset Skybox for bundle default Exception: Could not find asset Skybox for bundle default
[C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.1-beta\Targets\Paradox.targets(171,5)]: Error: выход из команды ""C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.1-beta\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerApp.exe"  --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\Bin\Windows-Direct3D11\Debug\data" --build-path="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\MyGame2.Windows\..\obj\data" --package-file="E:\MY\C#\Paradox3D\Games\MyGame2\MyGame2\MyGame2.Windows\..\MyGame2.pdxpkg" --log-pipe="net.pipe://localhost/SiliconStudio.Assets.Editor.ffe88fa1-797c-4a5e-b0c3-4f6311ddee5b"" с кодом 1.

But if I have removed skybox, it building is success.

**Comment by xen2** [comment]
Thanks for the feedback.
What is your GPU? (when we prefilter skybox, we need a DX11 GPU)

**Comment by codedraft** [comment]
I have NVIDIA GeForce GT 525M. And DirectX11 on my OS.
.

**Comment by seprab** [comment]
I have the same problem: [AssetCompiler(0,0)]: Error: Asset [Skybox] failed to compile.... bla bla
NVIDIA Quadro FX 5800 4gb

**Comment by xenux** [comment]
Do you have the error in English by the way? would be easier.

**Comment by xenux** [comment]
The R32G32B32A32_FLOAT pixel format with unordered access view is probably not supported by your graphic cards. The problem is that judging from https://msdn.microsoft.com/en-us/library/windows/desktop/dn914603(v=vs.85).aspx, other fallback formats such as R16G16B16A16_FLOAT are by transitivity not supported too.

**Comment by Zulusas** [comment]
I have this problem too (NVIDIA GeForce GT 525M). It is possible to use simpler default skybox for low-end machines?

**Comment by xenux** [comment]
The problem is not the skybox itself but its compilation. With current lighting system, we need to generate pre-filtered textures for each skybox used in the game in order to speed up lighting computations at run time. This generation process currently requires the use of the R32G32B32A32_FLOAT pixel format with unordered access. 
We will try to see if we can get around this some how.

**Comment by jwollen** [comment]
We just releases version 1.5.2 which should fix most Skybox-issues. Let us know if it works for you, if you have time to test it.
