### ISSUE TITLE
Support for Portable Class Library?

### ISSUE THREAD

**Issue by zmaruo** [SiliconStudio/xenko#273]
Hi,

I have no game development experience until past few weeks.

I created a new project using Paradox 1.2.2-beta. Opened the solution in Visual Studio 2015. Found 2 projects:
* MyGame.Game
* MyGame.Windows

I guess 'MyGame.Game' is where I should put my code. It's target framework is: .NET Portable Subset (.NET Framework 4.5.1, Windows 8.1, Windows Phone 8.1).

![2015-08-13_12-38-38](https://cloud.githubusercontent.com/assets/13757584/9242748/781323ec-41b9-11e5-845e-c51fe86d238d.png)

I added a Portable Class Library which also targets .NET 4.5.1, Windows 8.1, and Windows Phone 8.1, and tried to add a reference from 'MyGame.Game' to the PCL, but got the following error:

"Unable to add a reference to project 'ClassLibrary1'. The current project does not support references to Portable Library projects."
![2015-08-13_12-39-38](https://cloud.githubusercontent.com/assets/13757584/9242744/6d4ff048-41b9-11e5-9f0f-4ab978ea38ec.png)

So it seems Paradox doesn't support PCL yet, any plan to support PCL in the future?

I plan to develop some AI code that will be shared by my games and applications that run on many platforms, if there is no plan to support PCL, any ways to workaround this?

Thanks.

**Comment by xoofx** [comment]
Could you try to add the reference directly by editing the csproj?

**Comment by zmaruo** [comment]
Gave it a try, but got a warning icon in the Solution Explorer (see image below), and cannot reference class in the PCL from the 'MyGame.Game' project.

![2015-08-13_13-44-00](https://cloud.githubusercontent.com/assets/13757584/9243319/c18b1bf8-41c1-11e5-9dbc-481baaa364a3.png)

**Comment by xoofx** [comment]
Just tested and it is working here with a plain PCL projects created and adding the reference directly in VS. This is how my PCL is configured:
![pcl](https://cloud.githubusercontent.com/assets/715038/9243565/0cb90a94-41cd-11e5-801a-5b07ed8db580.jpg)

Could you double check?

**Comment by zmaruo** [comment]
Thanks for the screenshots. I did simple tests and I think it's a compatibility issue between Paradox and Visual Studio **2015**.

I can successfully add reference from the 'MyGame.Game'  project to PCL in Visual Studio **2013**, but when repeating the same procedure in VS **2015**, I got the same error as my first post.

**Comment by xoofx** [comment]
Weird, I tried also on VS 2015 and it is working...

**Comment by zmaruo** [comment]
Oh that is wired. I just tried again, and got same result as my previous post.

Not sure if it's related, I noticed one different between your screenshot and mine: My PCL has more optional targets than yours (my PCL was created in VS 2013).

In Visual Studio 2013:
![2015-08-13_14-30-25](https://cloud.githubusercontent.com/assets/13757584/9243905/71384138-41c8-11e5-84fb-35eebf31ce21.png)

In Visual Studio 2015:
![2015-08-13_14-28-38](https://cloud.githubusercontent.com/assets/13757584/9243900/696eb7a2-41c8-11e5-9df8-e325c8035abd.png)

**Comment by zmaruo** [comment]
My system configurations:
* Windows 10 64bit Enterprise (upgraded from Windows 8.1 Enterprise)
* Visual Studio 2013 Ultimate
* Visual Studio 2015 Enterprise

**Comment by xoofx** [comment]
Yes, I don't have installed Xamarin PCL, so there might be a conflict here, not sure why, but we will check this, thanks.

**Comment by sinkingsugar** [comment]
I cannot repro this issue. I have Xamarin and everything installed as well. It all just works fine following the steps above. Might have been an old xamarin version issue, not sure. btw, I have vs 2015 update 2.

**Comment by manu-silicon** [comment]
@zmaruo Follow the suggestions from issue #273 to fix this incompatibility. Next version of GameStudio will generate the proper project files.

**Comment by Scellow** [comment]
I found the solution, the Target Framework have to be the same for every projects in the solution
