### ISSUE TITLE
Paradox1.2.2 Cannot Startup

### ISSUE THREAD

**Issue by TracyLestrade** [SiliconStudio/xenko#295]
Paradox Version: 1.2.2-beta
GameStudio Version: 4
Current Directory: C:\Program Files\Silicon Studio Corp\Paradox
Command Line Args: /LauncherWindowHandle 262888
OS Version: Microsoft Windows NT 6.2.9200.0 (x86)
Processor Count: 4
Video configuration:
GPU 1
BitsPerPel: 32
Caption: Microsoft 基本显示适配器
Description: Microsoft 基本显示适配器
DeviceName: Microsoft 基本显示适配器
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: Microsoft 基本显示适配器
SpecificationVersion: 1025
Exception: InvalidOperationException: Error while loading default package from [C:/Program Files/Silicon Studio Corp/Paradox/GamePackages/Paradox.1.2.2-beta\Paradox.pdxpkg]: []: Error: Error while pre-loading package [C:\Program Files\Silicon Studio Corp\Paradox\GamePackages\Paradox.1.2.2-beta\Paradox.pdxpkg]. System.BadImageFormatException: 未能加载文件或程序集“SiliconStudio.Paradox.Importer.Assimp, Version=1.0.5701.32808, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。试图加载格式不正确的程序。
文件名:“SiliconStudio.Paradox.Importer.Assimp, Version=1.0.5701.32808, Culture=neutral, PublicKeyToken=null”
   在 System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   在 System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   在 System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   在 System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   在 System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   在 System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   在 SharpYaml.Serialization.AttributeRegistry.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   在 SiliconStudio.Core.Yaml.YamlSerializer.AtributeRegistryFilter.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   在 SharpYaml.Serialization.AssemblyRegistry.RegisterAssembly(Assembly assembly, IAttributeRegistry attributeRegistry)
   在 SharpYaml.Serialization.SerializerSettings.RegisterAssembly(Assembly assembly)
   在 SiliconStudio.Core.Yaml.YamlSerializer.CreateSerializer(Boolean keepOnlySealedOverrides, Serializer& localSerializer)
   在 SiliconStudio.Core.Yaml.YamlSerializer.GetYamlSerializer(Boolean keepOnlySealedOverrides)
   在 SiliconStudio.Core.Yaml.YamlSerializer.Deserialize(Stream stream, Type expectedType, SerializerContextSettings contextSettings)
   在 SiliconStudio.Assets.Serializers.AssetYamlSerializer.Load(Stream stream, String assetFileExtension, ILogger log)
   在 SiliconStudio.Assets.AssetSerializer.Load(Stream stream, String assetFileExtension, ILogger log)
   在 SiliconStudio.Assets.AssetSerializer.Load(String filePath, ILogger log)
   在 SiliconStudio.Assets.AssetSerializer.Load[T](String filePath, ILogger log)
   在 SiliconStudio.Assets.Package.LoadRaw(ILogger log, String filePath)

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

   在 SiliconStudio.Assets.PackageStore..ctor(String installationPath, String defaultPackageName, String defaultPackageVersion)
   在 SiliconStudio.Assets.PackageStore.<.cctor>b__4()
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 System.Lazy`1.get_Value()
   在 SiliconStudio.Assets.PackageStore.get_Instance()
   在 SiliconStudio.Assets.PackageSession..ctor(Package package)
   在 SiliconStudio.Assets.PackageSession..ctor()
   在 SiliconStudio.Paradox.GameStudio.Program.<Startup>d__d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.Run()
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 SiliconStudio.Paradox.GameStudio.Program.Main()

**Comment by TracyLestrade** [comment]
"SiliconStudio.Paradox.Importer.Assimp" I can find it.Why problem occured

**Comment by Benlitz** [comment]
Hi,

It seems that your version of Windows is 32 bits. Unfortunately, you need a 64 bits Windows to create games with Paradox.

**Comment by TracyLestrade** [comment]
Understood，thank you for your help.



At 2015-09-04 18:58:29, "Benlitz" <notifications@github.com> wrote:


Hi,

It seems that your version of Windows is 32 bits. Unfortunately, you need a 64 bits Windows to create games with Paradox.
