### ISSUE TITLE
Suggestion: Private WorldMatrix setter

### ISSUE THREAD

**Issue by wanderwurst** [SiliconStudio/xenko#301]
Just a minor detail here, I only mention it because it took me quite some time: The Intellisense help for the Transformation.WorldMatrix states that it gets or sets the transformation.
I was asuming that setting it does automatically cause all the calculations through the parent tree to finally update the local matrix (which would have been very handy for my cause).
Maybe it would lessen the confusion if the setter just wasn't publicly available (or add a note to the Intellisense help that it doesnt do any math)?

**Comment by xenux** [comment]
Hi wanderwurst,

The world matrix field has not be made into a property for performance purposes (avoid copies generated at each access by properties). 
We improved the intellisense comments and specified that the user is not supposed to set it. 
Changes will be include in next release.

**Comment by wanderwurst** [comment]
Thanks for the feedback, highly appreciated
