### ISSUE TITLE
Build in Paradox Studio fails on post-build step

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#319]
Hi,
My post-build steps fails, because $(SolutionDir) is undefined if I build project in Paradox Studio. Others macros are fine.

**Comment by xenux** [comment]
Hi, 

Did you load your project from the package or the solution? The $(SolutionDir) is undetermined (and thus undefined) when loading from a package (a package is not directly connected to a solution and could possibly be part of several solutions).
Could you try loading from the solution your package is contained into and see if it works properly?

**Comment by EmptyKeys** [comment]
If I open solution in Visual Studio I can build it without problem. The issue is that even the Paradox Studio knows directory of solution, $(SolutionDir) macro is undefined. So the build fails.

[C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(4713,5)]: Error: The command "CD "*Undefined*packages\EmptyKeysUI_Generator*\tools"

**Comment by xenux** [comment]
Sorry I meant did you open your project in the Studio from the solution .sln file or the .pdxpkg file?

**Comment by EmptyKeys** [comment]
Hmm I see. I'm using launcher and I see solution bellow the name, so I guess launcher is opening solution. I can see name of the solution in the title of Paradox Studio window.

**Comment by xenux** [comment]
This have been fixed. The variable will be available from next paradox release. :)

**Comment by EmptyKeys** [comment]
Cool, thanks
