### ISSUE TITLE
Memory leaks with Entity.AddChild()

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/xenko#321]
There is memory leaks with Entity.AddChild() when i trying to remove/dispose entities from Parent entity. I am working on voxel engine, so i need many dynamic entities (dinamicaly add/remove/dispose entities (chunks) ). 

I have attached test project with problem:
https://dl.dropboxusercontent.com/u/46052374/Material113.rar

When you hit F2, all entities must be removed from Scene and disposed. Task Manager is showing that memory is not released. When you hit F1/F2 several times - memory usage is increasing.

**Comment by Toasterthegamer** [comment]
I've also seen this issue. It's either not freeing up the unmanaged memory or the garbage collector isn't collecting the objects because they are still in use.

**Comment by xoofx** [comment]
Thanks for the report. This is fixed in our internal branch and should be released hopefully early next week.
