### ISSUE TITLE
Click event bug

### ISSUE THREAD

**Issue by PantsStatusZero** [SiliconStudio/xenko#322]
ButtonBase.Click should be:

public event EventHandler<RoutedEventArgs> Click
        {
            add
            {
                RemoveHandler(ClickEvent, value);
                AddHandler(ClickEvent, value);
            }
            remove
            {
                RemoveHandler(ClickEvent, value);
            }
        }

Has it currently is, if a programmer tries to bind a single event to a button twice the button will brake.

**Comment by xenux** [comment]
Hi !
Sorry I am not sure to understand what is the problem here. 
If you register twice to the same event, your function is called twice. It is the default behavior of C#. I am missing something?

**Comment by sinkingsugar** [comment]
I don't see anything wrong. Can we close this?
