### ISSUE TITLE
application won't start

### ISSUE THREAD

**Issue by boobeebah13** [SiliconStudio/xenko#327]
it told me to paste this in:
Launcher Version: 1.3.3
Current Directory: F:\
Command Line Args: 
OS Version: Microsoft Windows NT 6.2.9200.0 (x64)
Processor Count: 4
Video configuration:
GPU 1
BitsPerPel: 32
Caption: NVIDIA GeForce GTX 960
Description: NVIDIA GeForce GTX 960
DeviceName: NVIDIA GeForce GTX 960
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: NVIDIA GeForce GTX 960
SpecificationVersion: 1025
Exception: ArgumentNullException: Value cannot be null.
Parameter name: rootDirectory
   at SiliconStudio.Assets.NugetStore..ctor(String rootDirectory, String configFile, String overrideFile)
   at SiliconStudio.LauncherApp.Launcher.RunSafe()

so... just read this and tell what the hell is going on.

**Comment by Benlitz** [comment]
Hi,

Did you install Paradox in the root folder of a drive? It seems that you are trying to run Paradox from F:\
Installation in the root directory of a drive in not supported.
If this is the case, try to reinstall it in a different location, such as F:\Paradox.
