### ISSUE TITLE
Case issues with EditText

### ISSUE THREAD

**Issue by donnyv** [SiliconStudio/xenko#330]
EditText enters everything as lowercase, even if caps lock is on.

**Comment by donnyv** [comment]
Just noticed it doesn't accept decimal point either. Probably need to do a test with all secondary characters.

**Comment by xenux** [comment]
Ok thanks :)

**Comment by stephanbe** [comment]
We reproduced the bug, see [here](http://answers.xenko.com/questions/1795/edittext-ignores-non-alphanumeric-characters.html#answer-1797)

**Comment by xen2** [comment]
Duplicate of #50, closing that one
