### ISSUE TITLE
"Save current project" ignores the undo

### ISSUE THREAD

**Issue by EternalTamago** [SiliconStudio/xenko#343]
Hello.

1. Add a built-in script to a project in the Xenko studio.
2. Undo(CTRL+Z).
3. Save the project.
4. Reload the project.
-> There is the built-in script in the project.

Xenko 1.5.0-beta / Launcher v1.4.2
Windows 10 Pro x64

**Comment by Kryptos-FR** [comment]
Thanks for the report. It is fixed in 1.5.1-beta.
