### ISSUE TITLE
about TestImportModelSimple in [SiliconStudio.Xenko.Assets.Tests]

### ISSUE THREAD

**Issue by leaverChina** [SiliconStudio/xenko#348]
Excuse me. I build and launch the "SiliconStudio.Xenko.Assets.Tests" project, I found the code
"var assetItem = project.Assets.FirstOrDefault(item => item.Asset is EntityGroupAsset);"
is return null, why ?

And also, the Assets in PackageSession just include SkeletonAsset, MaterialsAsset, ModelAsset and RawAsset. There is no EntityGroupAsset exit.

**Comment by leaverChina** [comment]
why invalid line52 in ModelAssetImporter.cs 

"var isImportingEntity = importParameters.IsTypeSelectedForOutput<EntityGroupAsset>();“

**Comment by jwollen** [comment]
There was previously an EntityAsset and models could be imported to such an asset. This is not the case anymore, so this code/test is now disabled.
