### ISSUE TITLE
Issues about import a file

### ISSUE THREAD

**Issue by leaverChina** [SiliconStudio/xenko#349]
I want to import a OBJ format file, and generate a data folder for rendering.

What can I do?

Here is my code after reading the xenko source code[ModelAssetTests.cs]

var file = Path.Combine(Environment.CurrentDirectory, @"scenes\triangle.obj");
// Create a project with an asset reference a raw file
var project = new Package { FullPath = Path.Combine(Environment.CurrentDirectory, "ModelAssets", "ModelAssets" + Package.PackageFileExtension) };

var importSession = new AssetImportSession(session);
importSession.AddFile(file, project, UDirectory.Empty);

var stageResult = importSession.Stage();
importSession.Import();
session.Save();

what should I do next？

**Comment by jwollen** [comment]
Packages and related classes are meant to be used internally at design-time.
You can use the GameStudio to import Model assets from *.obj files and load them at run-time using AssetManager.Load(). Have a look at http://doc.xenko.com/1.5/manual/engine/asset-manager/index.html.
