### ISSUE TITLE
Duplicating an entity that has a "collider shape"

### ISSUE THREAD

**Issue by EternalTamago** [SiliconStudio/xenko#350]
Hello.

The editor crashes by changing the order of the entities after duplicating an entity that has a collider shape.

[steps to reproduce]
1. Create a new game project.
2. Add the physics component to the sphere entity that is placed by default.
3. Add a rigidbody element and select a sphere shape as the collider shape.
4. Duplicate the entity in the scene editor. ("Duplicate selected entities")
5. Move the duplicate entity to the higher in the list.

The editor quit without error message.

Thanks.

Xenko 1.5.2-beta / Launcher v1.4.3
Visual Studio 2015 Community
Windows 10 Pro x64

**Comment by sinkingsugar** [comment]
Thanks for the report, I fixed it internally! nice catch!
Will be included in the next release.
