### ISSUE TITLE
Xenko game studio won't launch

### ISSUE THREAD

**Issue by Rubikoid** [SiliconStudio/xenko#353]
Here is the log. I tried to start 1.4 version, but got a similar error.

Xenko Version: 1.5.2-beta
GameStudio Version: 4
Current Directory: C:\Program Files (x86)\Xenko
Command Line Args: 
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1 (x64)
Processor Count: 4
Video configuration:
GPU 1
BitsPerPel: 32
Caption: NVIDIA GeForce GT 620M
Description: NVIDIA GeForce GT 620M
DeviceName: NVIDIA GeForce GT 620M
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 9.18.13.4052
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: NVIDIA GeForce GT 620M
SpecificationVersion: 1025
Exception: InvalidOperationException: Error while loading default package from [C:/Program Files (x86)/Xenko/GamePackages/Xenko.1.5.2-beta\Xenko.xkpkg]: []: Error: Error while pre-loading package [C:\Program Files (x86)\Xenko\GamePackages\Xenko.1.5.2-beta\Xenko.xkpkg]. System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "SiliconStudio.Xenko.Importer.Assimp.dll" либо одну из их зависимостей. Не найден указанный модуль.
Имя файла: 'SiliconStudio.Xenko.Importer.Assimp.dll'
   в System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   в System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   в System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   в System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   в System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   в SharpYaml.Serialization.AttributeRegistry.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   в SharpYaml.Serialization.AssemblyRegistry.RegisterAssembly(Assembly assembly, IAttributeRegistry attributeRegistry)
   в SiliconStudio.Core.Yaml.YamlSerializer.CreateSerializer(Serializer& localSerializer) в C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core.Design\Yaml\YamlSerializer.cs:строка 251
   в SiliconStudio.Core.Yaml.YamlSerializer.GetYamlSerializer() в C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core.Design\Yaml\YamlSerializer.cs:строка 229
   в SiliconStudio.Core.Yaml.YamlSerializer.GetSerializerSettings() в C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core.Design\Yaml\YamlSerializer.cs:строка 208
   в SiliconStudio.Assets.AssetMigration.MigrateAssetIfNeeded(AssetMigrationContext context, PackageLoadingAssetFile loadAsset, String dependencyName, PackageVersion untilVersion) в C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\AssetMigration.cs:строка 56
   в SiliconStudio.Assets.Package.LoadRaw(ILogger log, String filePath) в C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\Package.cs:строка 667

   в SiliconStudio.Assets.PackageStore..ctor(String installationPath, String defaultPackageName, String defaultPackageVersion) в C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\PackageStore.cs:строка 79
   в SiliconStudio.Assets.PackageStore.<>c.<.cctor>b__29_0() в C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\PackageStore.cs:строка 24
   в System.Lazy`1.CreateValue()
   в System.Lazy`1.LazyInitValue()
   в SiliconStudio.Assets.Templates.TemplateManager.FindTemplates() в C:\TeamCity\work\e71632f3cedbf5cf\sources\assets\SiliconStudio.Assets\Templates\TemplateManager.cs:строка 57
   в SiliconStudio.Assets.Editor.Components.TemplateDescriptions.NewOrOpenSessionTemplateCollectionViewModel..ctor(IViewModelServiceProvider serviceProvider)
   в SiliconStudio.Assets.Editor.Components.TemplateDescriptions.Views.NewOrOpenSessionWindow..ctor()
   в SiliconStudio.Xenko.GameStudio.Program.<Startup>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в SiliconStudio.Xenko.GameStudio.Program.Main()

**Comment by Benlitz** [comment]
Hello,

Did you change the location to install Xenko during the installation? The default location should be `C:\Program Files\Silicon Studio\Xenko `but the Game Studio is trying to load from `C:\Program Files (x86)\Xenko` on your computer.
Could you check if both folders exists? If so, could you check if they contain a `GamePackages `folders, and if there is a `Xenko.1.5.2-beta `folder inside it?

It sounds like something went wrong during the installation. If the problem persists, could you try to uninstall and reinstall Xenko?

Sorry for the trouble!

**Comment by Rubikoid** [comment]
Yes, i change'd location, but at the second install.
At first, i have the error, but with other path in log.
Yes, `GamePackages` exists. And `Xenko.1.5.2-beta` too.

**Comment by Rubikoid** [comment]
Any ideas?

**Comment by sinkingsugar** [comment]
I see a file not found for : SiliconStudio.Xenko.Importer.Assimp.dll
Can you search if it's there?

**Comment by Rubikoid** [comment]
Ookey. C:\Program Files (x86)\Xenko\GamePackages\Xenko.1.5.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Xenko.Importer.Assimp.dll - here that dll

**Comment by Benlitz** [comment]
This assembly supposed to load a C++ DLL (located in the x64 subdirectory). Normally, during Xenko installation, the prerequisites to load this DLL should be installed, but maybe something went wrong. Could you check that you have Microsoft Visual C++ 2013 Redistributable (x64) installed on your computer? You can find this information in the Program and Features menu of the Control Panel.
If it is not present, could you try to install it from Microsoft website? x64 should be enough.
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by Rubikoid** [comment]
Oookey. I reinstall mvc++ from that link.
Problem solved.
Close issue?
