### ISSUE TITLE
Paradox uninstall doesn't remove everything

### ISSUE THREAD

**Issue by InfiniteProductions** [SiliconStudio/xenko#355]
After removing Paradox, I have this harmless error in VS2013, compiling a project that don't use Paradox or Xenko at all (in french, it just said it can't find assembly or a dependency):

Error	1	Impossible de charger le fichier ou l'assembly 'SiliconStudio.Paradox.VisualStudio.Commands' ou une de ses dépendances. Le fichier spécifié est introuvable.		0	0	

I add this issue cause it may still occurr with Xenko.

**Comment by Kryptos-FR** [comment]
The uninstall of Visual Studio has been fixed in Xenko. For old Paradox, you have to remove the plugin manually. See alsohttp://answers.xenko.com/questions/1727/uninstall-paradox-from-visual-studio.html
