### ISSUE TITLE
Duplicate Display order for EntityComponents should be handled gracefully (acceptable)

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#357]
Hi,

EntityComponent authors should not have to worry about there component's display order clashing with others. Currently causes errors loading projects and can cause Game Studio to crash if you try a component with a duplicate display order

Cheers,
dfkeenan

**Comment by dfkeenan** [comment]
So I think you only get a warning if you set the `Order` property of the `DisplayAttribute`.  But it errors if you don't set one, at least if you don't use the `ComponentOrderAttribute`.   For some reason I can't find the `ComponentOrderAttribute` type even though the project references the `SiliconStudio.Xenko.Engine` assembly and I have a using statement for the `SiliconStudio.Xenko.Engine` namespace.

**Comment by dfkeenan** [comment]
Turns out `ComponentOrderAttribute` is new and not in the currently released version.  Online documentation is current with master rather then the currently released version if you go to http://doc.xenko.com/latest/api/.  That's a trap for new players.

**Comment by xen2** [comment]
Doc is supposed to be generated from master-1.5 branch, we will check what is wrong.

**Comment by dfkeenan** [comment]
If the documentation has been fixed up (as @xen2 ) indicated in gitter chat. I am happy for this to be closed.
