### ISSUE TITLE
Crash on script add

### ISSUE THREAD

**Issue by jason-wilmans** [SiliconStudio/xenko#358]
Tried to add a relatively simple script to an entity. The error itself is probably my fault. But it took the whole scene editor down with it.

![entitystate](https://cloud.githubusercontent.com/assets/1858567/13403129/c630c8c0-df13-11e5-8930-5ab90f817cde.PNG)

The script looks like this: 

``` csharp
public class TextScript : StartupScript
{
    private SpriteBatch batch;
    private Vector2 screenSize;
    private SceneDelegateRenderer fontRenderer;
    public SpriteFont Font { get; set; }

    public override void Start()
    {
        base.Start();

        batch = new SpriteBatch(GraphicsDevice.RootDevice)
        {
            VirtualResolution = new Vector3(GraphicsDevice.RootDevice.Viewport.Size, 1000)
        };
        screenSize = new Vector2(GraphicsDevice.BackBuffer.Width, GraphicsDevice.BackBuffer.Height);

        var scene = SceneSystem.SceneInstance.Scene;
        var compositor = (SceneGraphicsCompositorLayers)scene.Settings.GraphicsCompositor;
        fontRenderer = new SceneDelegateRenderer(DrawFont);
        compositor.Master.Renderers.Add(fontRenderer);
    }

    private void DrawFont(RenderContext arg1, RenderFrame arg2)
    {
        batch.Begin();
        var text = "None - This is a sample sentence.";
        batch.DrawString(Font, text, Vector2.One, Color4.White);
        batch.End();
    }

    protected override void Destroy()
    {
        base.Destroy();

        var scene = SceneSystem.SceneInstance.Scene;
        var compositor = (SceneGraphicsCompositorLayers)scene.Settings.GraphicsCompositor;

        compositor.Master.Renderers.Remove(fontRenderer);
        batch.Dispose();
    }
}
```
# Reported error 

Xenko Version: 1.5.3-beta
GameStudio Version: 4
Default session graphics profile: Level_11_0
Current Directory: C:\Program Files\Silicon Studio\Xenko
Command Line Args: C:\Users\jason\Documents\Work\Uni\three-dee\1 - Code\ThreeDee\ThreeDee.sln
OS Version: Microsoft Windows NT 6.2.9200.0 (x64)
Processor Count: 6
Video configuration:
GPU 1
BitsPerPel: 32
Caption: AMD Radeon R9 200 / HD 7900 Series
Description: AMD Radeon R9 200 / HD 7900 Series
DeviceName: AMD Radeon R9 200 / HD 7900 Series
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: AMD Radeon R9 200 / HD 7900 Series
SpecificationVersion: 1025
Exception: TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.Activator.CreateInstance(Type type)
   bei SiliconStudio.Core.Reflection.ObjectFactory.NewInstance(Type objectType) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\core\SiliconStudio.Core\Reflection\ObjectFactory.cs:Zeile 118.
   bei SiliconStudio.Quantum.Commands.ChangeValueCommand.Invoke(Object currentValue, Object parameter, UndoToken& undoToken) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\presentation\SiliconStudio.Quantum\Commands\ChangeValueCommand.cs:Zeile 16.
   bei SiliconStudio.Presentation.Quantum.ModelNodeCommandWrapper.Redo(Object parameter, Boolean creatingActionItem) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\presentation\SiliconStudio.Presentation.Quantum\ModelNodeCommandWrapper.cs:Zeile 63.
   bei SiliconStudio.Presentation.Commands.CancellableCommand.ExecuteCommand(Object parameter, Boolean createActionItem) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\presentation\SiliconStudio.Presentation\Commands\CancellableCommand.cs:Zeile 100.
   bei SiliconStudio.Xenko.Assets.Presentation.SceneEditor.SceneNodeCommandWrapper.<>c__DisplayClass12_0.<Redo>b__0()
   bei SiliconStudio.Xenko.Assets.Presentation.SceneEditor.SceneNodeCommandWrapper.ProcessSceneCommand(Action assetAction, Func`2 sceneAction)
   bei SiliconStudio.Xenko.Assets.Presentation.SceneEditor.SceneNodeCommandWrapper.Redo(Object parameter, Boolean creatingActionItem)
   bei SiliconStudio.Presentation.Commands.CancellableCommand.ExecuteCommand(Object parameter, Boolean createActionItem) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\presentation\SiliconStudio.Presentation\Commands\CancellableCommand.cs:Zeile 100.
   bei SiliconStudio.Presentation.Commands.CancellableCommand.Execute(Object parameter) in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\presentation\SiliconStudio.Presentation\Commands\CancellableCommand.cs:Zeile 53.
   bei SiliconStudio.Presentation.Behaviors.OnEventCommandBehavior.OnEvent() in C:\TeamCity\work\e71632f3cedbf5cf\sources\common\presentation\SiliconStudio.Presentation\Behaviors\OnEventCommandBehavior.cs:Zeile 40.
   bei SiliconStudio.Assets.Editor.View.Behaviors.OnComboBoxClosedWithSelectionBehavior.OnEvent()
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei System.Windows.FrameworkElement.RaiseClrEvent(EventPrivateKey key, EventArgs args)
   bei System.Windows.Controls.ComboBox.OnIsDropDownOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   bei System.Windows.Controls.ComboBox.Close()
   bei System.Windows.Controls.ComboBoxItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei SiliconStudio.Xenko.GameStudio.Program.Main()

InnerException:
  NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
     bei SiliconStudio.Xenko.Engine.ScriptContext.get_GraphicsDevice() in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\ScriptContext.cs:Zeile 97.
     bei ThreeDee.TextScript..ctor() in C:\Users\jason\Documents\Work\Uni\three-dee\1 - Code\ThreeDee\ThreeDee\ThreeDee.Game\TextScript.cs:Zeile 18.

**Comment by Kryptos-FR** [comment]
Hello. A lot have changed since you reported your issue, do you still have similar crash with newer versions of Xenko?

**Comment by jason-wilmans** [comment]
I tested the script with 1.9.3. Almost every line had to be changed because the API changed so much. In that updated version, there is no crash. I also experience less crashes on script add in general.

So I guess this is fixed.
