### ISSUE TITLE
Analysis of 'Xenko' source code by PVS-Studio static code analyzer

### ISSUE THREAD

**Issue by InkViziT0r** [SiliconStudio/xenko#360]
Development team of proprietary PVS-Studio C/C++/C# static analyzer presents their report on the source code of 'Xenko' in the article, which contains the review of the most suspicious code fragments they discovered.

You can read article on the official site:
http://www.viva64.com/en/b/0379/

**Comment by xen2** [comment]
Thanks for the feedback, we fixed most important issues!
