### ISSUE TITLE
Editor. Wrong size of Maximized Window when working on two monitor system.

### ISSUE THREAD

**Issue by homoluden** [SiliconStudio/xenko#361]
I have laptop with smaller screen + big external monitor.
When I open Editor on bigger monitor and switch to maximized mode I get right part of the UI rendered off-screen. For example, Scene Properties goes out of the screen. The only way to access it is to switch to Normal Window state and adjust the size to the screen by resize grip.

**Comment by Kryptos-FR** [comment]
Thanks for the report. Could you give me your screen resolution (both laptop and external monitor)?

**Comment by Kryptos-FR** [comment]
It seems to happen only if the primary screen resolution is smaller than the secondary. As a workaround you can try to make your bigger screen (external monitor) the primary screen.

**Comment by homoluden** [comment]
Hi

Laptop: 1366x768
Ext.: 1920x1080

I believe the issue is related to the Windows feature to merge two desktops
into one screen. When I press PrintScreen without any Modificators (Ctrl or
Alt) it gives me one picture containing both desktops.

Hope it will help.

On Thu, Mar 10, 2016 at 5:35 AM, Nicolas Musset <notifications@github.com>
wrote:

> Thanks for the report. Could you give me your screen resolution (both
> laptop and external monitor)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiliconStudio/xenko/issues/361#issuecomment-194628270>
> .
>



-- 
Sincerely Yours,
               *Alexey Matveev *!

**Comment by homoluden** [comment]
"It seems to happen only if the primary screen resolution is smaller than
the secondary. As a workaround you can try to make your bigger screen
(external monitor) the primary screen."

I also think it is, because I had the same issue with one of the desktop
apps I implemented in past.

On Thu, Mar 10, 2016 at 5:35 AM, Nicolas Musset <notifications@github.com>
wrote:

> Thanks for the report. Could you give me your screen resolution (both
> laptop and external monitor)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiliconStudio/xenko/issues/361#issuecomment-194628270>
> .
>



-- 
Sincerely Yours,
               *Alexey Matveev *!

**Comment by homoluden** [comment]
I confirm Workaround is working on my side, but it needs me to refactor the way I'm working on my workstation. Someone can reject this workaround as too inconvenient.

**Comment by Kryptos-FR** [comment]
We will address this issue as soon as possible. Right now we have other issues that need to be fixed beforehand. Rest assured that the workaround is indeed temporary.

**Comment by Kryptos-FR** [comment]
The issue has been fixed internally and will be released soon.
