### ISSUE TITLE
Can't launch Xenko (any version) from inside the launcher

### ISSUE THREAD

**Issue by z16** [SiliconStudio/xenko#363]
I installed Xenko, open the launcher and download any version (tried with all, including 1.6). Once the download is finished, I try to launch it and get the following error message, upon which nothing happens and I'm still in the launcher:
![image](https://cloud.githubusercontent.com/assets/1635608/13889738/75c20820-ed48-11e5-8fab-c4e8c29676c6.png)

* I'm on Windows 10.
* I click on the download button and I see it downloading and subsequently installing the respective version.
* I have previously used Paradox on Windows 7 (old PC, same hard drive) with no issues. A Paradox install was still on the hard drive when I first tried installing Xenko, but I have since deleted it and it didn't help.
* I have tried installing to different directories on different physical drives, including the default directory.
* I have tried installing for only the current user and for everybody, with the same result.
* I also get another unique issue (at least I haven't heard it reported before) when trying to install the VS plugin. I have no idea if the two are related, but I [reported that in a different issue](https://github.com/SiliconStudio/xenko/issues/364).

Let me know if you need to know anything else.

**Comment by xen2** [comment]
Hello,

Tried to install on my E:\Xenko in case different drive or short folder was a problem but couldn't reproduce.

Could you please let us know the content of:
- Your SiliconStudioXenkoDir environment variable (it was not set from what I remember?)
- Your X:\Xenko folder (recursive file listing, i.e. from "dir /s", is probably good enough, zip file even better)

**Comment by Structed** [comment]
I have the exact same problem as you @z16, but the following things are different:

* Windows 7
* Never installed Xenko or  Paradox before
* Installed for all users, on D:\Xenko
* I didn't try different directories or "Just for me install"

Here are the infos @xen2 requested:
* SiliconStudioXenkoDir=D:\Xenko\
* Here's my directory listing: [dir.txt](https://github.com/SiliconStudio/xenko/files/187642/dir.txt)

**Comment by z16** [comment]
Sorry, was on vacation after I posted that.

* SiliconStudioXenkoDir is `X:\Xenko\`
* My directory listing: https://gist.github.com/z16/f41aeb2b7321f51e1ebb

@Structed: Do you have the same issue with [installing the visual studio plugin](https://github.com/SiliconStudio/xenko/issues/364) that I do? Would give me some piece of mind to know they're related, and not two separate rare issues...

**Comment by xen2** [comment]
@z16 @Structed Could you please let us know if latest launcher (should auto update) works better for you? Thanks!

**Comment by z16** [comment]
I tried starting the launcher, it told me a new version was available and that it was downloading it. Then I got a popup about missing prerequisites:
![image](https://cloud.githubusercontent.com/assets/1635608/14402266/8b5d2234-fe30-11e5-841c-87d87e478b44.png)

When I click "OK" it goes away and immediately reappears. It never seems to actually install MSBuild 2013. The popup just appears over and over again. When I click "Cancel" and try to run the launcher again I don't even get into the launcher menu anymore, this popup just pops up and refuses to go away.

**Comment by xen2** [comment]
Hmm, do you actually have MSBuild 2013 installed or not?

**Comment by xen2** [comment]
Also, what happens if you manually run `%SiliconStudioXenkoDir%\Prerequisites\launcher-prerequisites.exe` ?

**Comment by z16** [comment]
I'm not sure, to be honest. I do have a folder on my hard drive for it, but I cannot find an entry for it in the registry. I do have a registry entry for MSBuild 2015 though. Is there a definitive way to check?

Running `%SiliconStudioXenkoDir%\Prerequisites\launcher-prerequisites.exe` pops up two windows that very quickly disappear (too quickly to see what's going on), then nothing. It's the same thing that happens when I click "OK" in the dialogue (sorry, should have mentioned that windows pop up and immediately disappear).

**Comment by xen2** [comment]
Weird that the prerequisite installer doesn't try to install it.

Please try to install https://www.microsoft.com/en-us/download/details.aspx?id=40760 manually, and let us know if that fix the problem for you.

**Comment by z16** [comment]
Apparently I already had it installed, but I just ran a repair on it. However, it tells me that the PC must be restarted now, and I'm currently not in a position to comply lol. I'll see if I can do it later today and see if that helps. Fwiw I still don't see an entry for it in the registry, but it might as well be this is what happens after the restart. The Xenko launcher warning about missing prerequisites also hasn't gone away yet, but that could also be explained by the lack of a registry entry.

**Comment by z16** [comment]
Actually, seeing how I'll be gone all day I probably won't get to restart until tomorrow... I'll let you know tomorrow, if you haven't thought of anything else by then.

**Comment by xen2** [comment]
Uploaded a new 1.5.1 version (if you are stuck, you can download it from website: http://xenko.com/download). It checks for both 32 and 64 bit msbuild.

I suppose you have MSBuild 12 installed for 32 bit only (somehow, maybe by some other product). I will investigate about this further.

**Comment by xen2** [comment]
Update: new launcher 1.5.2 doesn't require MSBuild 2013 anymore, should make everything simpler (it was planned to do so in the future to minimize update risks, but turns out it was even more problematic to keep it).

**Comment by Structed** [comment]
Original problem is fixed for me - thanks!

**Comment by z16** [comment]
I managed to try it sooner than I thought. The problem is solved for me, as is the one I linked to above (the VS plugin not being able to install). All is right with the world again :)

Thanks!

**Comment by xen2** [comment]
Cool, thanks for testing and sorry it took so long!
