### ISSUE TITLE
missing "SiliconStudio.Xenko.Assets.Presentation.Templates"

### ISSUE THREAD

**Issue by VeryVery** [SiliconStudio/xenko#366]
Sorry, I first build this engine, I found the folder "40-Editor" all is unavailable in solution 'Xenko' (82 projects) when launching "LaunchWindowsSolution.bat" script.

But the "SiliconStudio.Xenko.SamplesBootstrapper.csproj" need to references SiliconStudio.Xenko.Assets.Presentation

The source code in Program.cs line 6 -> using SiliconStudio.Xenko.Assets.Presentation.Templates;

**Comment by Benlitz** [comment]
Hello, 

The project "SiliconStudio.Xenko.SamplesBootstrapper.csproj" is used internally for automated test and is not needed at all to use the engine. To avoid confusion, we'll remove it from the repository.
