### ISSUE TITLE
Version 1.6, Buffer, SpriteEffect and MatrixTransform

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#367]
Hi, I'm working on render support for 1.6 version and have pretty much everything working like in version 1.5.x except shapes.

For some strange reason shapes (rectangle, ellipse etc.) are not working. That part of the UI is using Buffers and SpriteEffect. I create vertex buffer and draw it with that effect.

This is old code:

https://github.com/EmptyKeys/UI_Engines/blob/master/EmptyKeys.UserInterface.Xenko/Renderers/XenkoRenderer.cs

Problematic method in new version is DrawGeometry. New version is bellow. It looks like MatrixTransform is somehow ignored or doing something else than before. Shapes are rendered in the middle of the screen. Any idea what could be the reason?

        private Matrix view = Matrix.LookAtRH(new Vector3(0.0f, 0.0f, 1.0f), Vector3.Zero, Vector3.UnitY);

        private void DrawGeometry(GeometryBuffer buffer, PointF position, float depth)
        {
            if (isSpriteRenderInProgress)
            {
                spriteBatch.End();
            }

            Matrix world = Matrix.Translation(position.X, position.Y, depth);
            Matrix projection = Matrix.OrthoOffCenterRH(0, graphicsContext.CommandList.Viewport.Width, graphicsContext.CommandList.Viewport.Height, 0, 1.0f, 1000.0f);

            //Vector3 resolution = GetCurrentResolution(graphicsContext.CommandList);
            //SpriteBatch.CalculateDefaultProjection(ref resolution, out projection);

            Matrix worldView;
            Matrix.MultiplyTo(ref world, ref view, out worldView);
            Matrix result;
            Matrix.MultiplyTo(ref worldView, ref projection, out result);            

            XenkoGeometryBuffer paradoxBuffer = buffer as XenkoGeometryBuffer;            
            paradoxBuffer.EffectInstance.Parameters.Set(SpriteBaseKeys.MatrixTransform, result);
            paradoxBuffer.EffectInstance.Apply(graphicsContext);
            
            if (isClipped)
            {
                geometryPipelineState.State.RasterizerState = scissorRasterizerStateDescription;
            }
            else
            {
                geometryPipelineState.State.RasterizerState = geometryRasterizerStateDescription;
            }

            switch (buffer.PrimitiveType)
            {
                case GeometryPrimitiveType.TriangleList:
                    geometryPipelineState.State.PrimitiveType = PrimitiveType.TriangleList;
                    break;
                case GeometryPrimitiveType.TriangleStrip:
                    geometryPipelineState.State.PrimitiveType = PrimitiveType.TriangleStrip;
                    break;
                case GeometryPrimitiveType.LineList:
                    geometryPipelineState.State.PrimitiveType = PrimitiveType.LineList;
                    break;
                case GeometryPrimitiveType.LineStrip:
                    geometryPipelineState.State.PrimitiveType = PrimitiveType.LineStrip;
                    break;
                default:
                    break;
            }

            geometryPipelineState.State.RootSignature = paradoxBuffer.EffectInstance.RootSignature;
            geometryPipelineState.State.EffectBytecode = paradoxBuffer.EffectInstance.Effect.Bytecode;            
            geometryPipelineState.State.Output.CaptureState(graphicsContext.CommandList);
            geometryPipelineState.Update();
            graphicsContext.CommandList.SetPipelineState(geometryPipelineState.CurrentState);            

            graphicsContext.CommandList.SetVertexBuffer(0, paradoxBuffer.VertexBufferBinding.Buffer, 0, paradoxBuffer.VertexBufferBinding.Stride);            
            graphicsContext.CommandList.Draw(paradoxBuffer.PrimitiveCount);

            if (isSpriteRenderInProgress)
            {
                if (isClipped)
                {
                    spriteBatch.Begin(graphicsContext, SpriteSortMode.Deferred, null, null, null, scissorRasterizerStateDescription, null, 0);                    
                }
                else
                {
                    spriteBatch.Begin(graphicsContext);
                }
            }
        }

**Comment by EmptyKeys** [comment]
I have created very simple example of that issue. You can download it here.

http://emptykeys.com/Uploads/XenkoIssue.zip

Correct result should be square on position 100, 100 with size of 10x10 pixels. 

I guess I'm doing something wrong, but can't find it.

**Comment by jwollen** [comment]
Thanks for digging into the new API already!

The problem here is a missing vertex layout. That causes the vertex positions to not arrive at the shader at all. To fix this, add this to your `MutablePipelineState`

```
geometryPipelineState.State.InputElements = xenkoBuffer.VertexBufferBinding.Declaration.CreateInputElements();
```

You may also want to store the `InputElementDescription[]` inside the `XenkoGeometryBuffer`, so it does not need to be recreated every draw.

**Comment by EmptyKeys** [comment]
Cool, it's working now! Thanks
