### ISSUE TITLE
Texture2DArray (v1.6) 

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/xenko#369]
Hi, 
There is some bug with Texture2DArray on v 1.6. Check attached samples.  Sample MyGame_1_5 is working properly (v1.5), while sample MyGame_1_6 is showing black screen. 

[MyGame_1_5.zip](https://github.com/SiliconStudio/xenko/files/187944/MyGame_1_5.zip)
[MyGame_1_6.zip](https://github.com/SiliconStudio/xenko/files/187945/MyGame_1_6.zip)

**Comment by jwollen** [comment]
Thanks for the report!

This has been fixed internally and will be part of the next bugfix release (1.6.1).
