### ISSUE TITLE
Asset path

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#372]
Hi,
I'm not sure if this is by design or just oversight. If you have asset in some directory you have to use '/', for Load method, because '\' is not working. Content manager will not find it.

**Comment by xen2** [comment]
This one is by designed, we use / for Xenko assets (same as the VFS system too).
We probably don't want to have both \ and / (slippery slope).

**Comment by EmptyKeys** [comment]
OK, I will replace it in my code then.
