### ISSUE TITLE
[Suggestion] Game PCL project type

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#373]
Hi,
You are using old PCL project type for Game projects. Please consider using latest project type. The only difference is this line (afaik):

    <ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>

**Comment by manu-silicon** [comment]
The `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` is for C# projects while `786C830F-07A1-408B-BD7F-6EE04809D6DB` is for Portable Class Library which is clearly the intent here. So your suggestions seems reasonable. If we were to keep things as is, what would be the impact? Are you getting some warnings or build errors?

**Comment by EmptyKeys** [comment]
Looks like that in some combination of installed stuff you are not able to reference "new" PCL project in "old" one. You can hack around it by changing project file by hand and it works, but VS 2015 will still show yellow warning on that reference. I can see this issue after reinstalling my comp so I only have VS 2015 Community Update 2 installed atm.

Think you can try it yourself. Open some of you examples. Create new PCL class library (the new type) in that solution, set the same PCL profile and try to add solution reference that library from ".Game" project. I get this error:

"Unable to add a reference to project 'ClassLibrary1'. The current project does not support references to Portable Library projects."

Maybe there is something else wrong with current generated ".Game" project, but I didn't have the time to find out. Changing to new PCL type solves the issue.

**Comment by sinkingsugar** [comment]
Hmm this might be related to this then https://github.com/SiliconStudio/xenko/issues/273

**Comment by manu-silicon** [comment]
Looks like we dropped the PCL project type to support VS Express a while back. See Issue #4. @sinkingsugar This is definitely related to #273 as in #273 it tries to load a project in which the library was added, whereas here VS 2015 will prevent addition.

**Comment by manu-silicon** [comment]
@EmptyKeys Fix will be available in next release. Thanks!
