### ISSUE TITLE
Fullscreen mouse issue

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#375]
Hi,
There is mouse issue with full screen. Mouse has wrong X,Y. You can replicate this issue by using SimpleTerrain example.

1) Create new SimpleTerrain example
2) Change code to this

    class SimpleTerrainApp
    {
        static void Main(string[] args)
        {
            using (var game = new Game())
            {
                game.GraphicsDeviceManager.PreparingDeviceSettings += GraphicsDeviceManager_PreparingDeviceSettings;
                game.Run();
            }
        }

        private static void GraphicsDeviceManager_PreparingDeviceSettings(object sender, SiliconStudio.Xenko.Games.PreparingDeviceSettingsEventArgs e)
        {
            var manager = sender as GraphicsDeviceManager;
            e.GraphicsDeviceInformation.PresentationParameters.BackBufferHeight = 1920;
            e.GraphicsDeviceInformation.PresentationParameters.BackBufferHeight = 1080;
            e.GraphicsDeviceInformation.PresentationParameters.IsFullScreen = true;
        }
    }
3) Mouse over the UI to observe the issue

BTW I have 3 monitors on my desktop, just saying, it could be related.

**Comment by xen2** [comment]
Thanks. We have some fixes for fullscreen coming for 1.6.1. We will check if this is fixed as well.

**Comment by sinkingsugar** [comment]
Switching resolution in that way is really not ideal actually. Switching it from game settings (within the editor) I could not reproduce it.
Switching the way you did is problematic, I will look into it. 
Please switching using something like this:
`
var game = (Game)Game;
game.GraphicsDeviceManager.PreferredBackBufferWidth = 1920;
game.GraphicsDeviceManager.PreferredBackBufferHeight = 1200;
game.GraphicsDeviceManager.IsFullScreen = true;
game.GraphicsDeviceManager.ApplyChanges();
`

**Comment by sinkingsugar** [comment]
Actually using the code you were using to fullscreen switch I could reproduce the other issue you posted #376... I'll look into it.

**Comment by sinkingsugar** [comment]
We are going to review the code related to those events, please use the way I suggested above from now on to switch resolution/fullscreen state.

**Comment by EmptyKeys** [comment]
Is there any event, where I can override GameSettings and set other stuff like vsync, depth stencil format, MultiSampleCount etc. before device is created?
I'm using PreparingDeviceSettings to do exactly that. When I want to change resolution of running game I'm using ApplyChanges and it's working "fine".

**Comment by sinkingsugar** [comment]
We moved PreparingDeviceSettings in a better location that should support your needs, just wait for the next upcoming release :)

**Comment by EmptyKeys** [comment]
cool thanks :)

**Comment by xen2** [comment]
Should be good with 1.6.1, please reopen if not.
