### ISSUE TITLE
Fullscreen, window and multimonitor

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#376]
Hi,
This is bit tricky issue and it's probably related to my multi monitor setup. I got 3 monitors with middle one being main. Monitor on the left is 2nd output on standalone GPU, monitor on the right is output of CPU graphic card. I'm running Windows 8.1 (all latest updates).

If I start my game in full screen, I can see edge of the window on the monitor on the right. I can even click on Close button, which will crash the game.

**Comment by xen2** [comment]
Thanks. @sinkingsugar made some fixes for fullscreen coming in 1.6.1. We will check if this is fixed as well.

**Comment by sinkingsugar** [comment]
I cannot replicate this issue in our current master so I assume it should be fine.
In the future release I re-implemented alt-enter, so on alt-enter I could not reproduce, as well as switching to fullscreen from the presenter.
I had the issue you mentioned with some other games/engines and home pc tho.. so it might just be windows os as well.

**Comment by sinkingsugar** [comment]
Please see #375, this happens if we switch to fullscreen in an unsupported way. ( we'll review that later to avoid that case )

**Comment by xen2** [comment]
Should be good with 1.6.1, please reopen if not.
