### ISSUE TITLE
Effect is never loaded if it has no effect values

### ISSUE THREAD

**Issue by dannsam** [SiliconStudio/xenko#378]
[`renderEffect.EffectValidator.EndEffectValidation`](https://github.com/SiliconStudio/xenko/blob/master/sources/engine/SiliconStudio.Xenko.Engine/Rendering/EffectValidator.cs#L67):
```
if (effectValuesValidated < EffectValues.Count)
{
    // Erase extra values
    EffectValues.Count = effectValuesValidated;
    return false;
}

return !effectChanged && effectValuesValidated == EffectValues.Count;
```

`EffectValues.Count` is 0 as well as `effectValuesValidated` -> the first condition always returns false
`effectChanged` is also `false` because I never call `ValidateParameter`
As a result, `EndEffectValidation` returns `true` when it's called from [`RootEffectRenderFeature` line 
327](https://github.com/SiliconStudio/xenko/blob/master/sources/engine/SiliconStudio.Xenko.Engine/Rendering/RootEffectRenderFeature.cs#L327) incorrectly assuming that the effect is still pending.

It's not an issue for proper effects, but(!) it confuses **SO** much when you're just trying to get your head around new rendering pipeline and it does not load your effect for some magical reasons.

**Comment by xen2** [comment]
Sorry about that one, noticed it on our end as well but 1.6.2 release was already underway.
Hopefully should be fixed in next one.

**Comment by dannsam** [comment]
Thanks, no worries, I use a workaround - calling ValidateParameter on a random parameter :)

**Comment by xen2** [comment]
I suppose simply starting with `effectChanged = true` should be good enough for all those cases.
