### ISSUE TITLE
Sprite Sheet Selection missing

### ISSUE THREAD

**Issue by vashero** [SiliconStudio/xenko#379]
I can not import previously created sprite sheets, and when I try to import new ones, it see's then only as textures.  previously created ones, when looking at frames, the property grid, shows an error occurred while loading properties of the selection.

One of many spritesheets, that I can no longer use.....
![4a_f_0](https://cloud.githubusercontent.com/assets/6729978/14228926/8913860c-f8eb-11e5-80e5-25c6cbb21828.png)

Even the premade spriteEntity project has this problem, see...

![image](https://cloud.githubusercontent.com/assets/6729978/14233202/70c9c402-f987-11e5-84d8-0a309666ffca.png)

And this was a newly created project, I didnt touch a thing.  Just was seeing if my project I was working on got corrupted somehow, or if it was Xenko.

**Comment by Benlitz** [comment]
Hi,

Sorry for this regression, we fixed it internally and will release an update during the week!
