### ISSUE TITLE
Group ignored on Particle

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#380]
Hi,
I think I found the bug with Particles ignoring group settings and always belong to Group 0 even if you set something else. You can try that on UI Particles example.

Load UI Particles example and delete 2nd Clear and Render Camera for Group1. Run example. You will see that particles are still visible.

**Comment by LautrecOfCarim** [comment]
Hi,
Thanks for the report, I confirmed the bug. It seems we have a regression, because it was working properly when the sample was first created. I'll look into it!

**Comment by LautrecOfCarim** [comment]
It was a simple issue, this patch should fix your problem:
[0001-Particles-Bug-fix-where-Group-for-particle-render-it.zip](https://github.com/SiliconStudio/xenko/files/214229/0001-Particles-Bug-fix-where-Group-for-particle-render-it.zip)

**Comment by xen2** [comment]
Note that in future version of Xenko, Entity.Group might be deprecated and replaced with another mechanism to provide better perf/control.

**Comment by EmptyKeys** [comment]
Thanks for fix, tho i will wait for next version.

BTW looks like same issue is on Background entity.

**Comment by LautrecOfCarim** [comment]
The Background had the same problem indeed. I double checked the other renderers and they should be fine. Thanks for the report!
