### ISSUE TITLE
skybox lighting

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/xenko#383]
Hi, i have some issues with skybox lighting. It seams, that skybox lighting is rotated. Check my demo.
[skyboxTest.zip](https://github.com/SiliconStudio/xenko/files/219209/skyboxTest.zip)

**Comment by jwollen** [comment]
Hi! Sorry for the late response.

In the demo, the normal map is not treated as such. You can change that by the `Format > Hint` to `NormalMap` on the texture asset. In the future, we plan to automatically recognize normal maps when importing.
