### ISSUE TITLE
"Invalid" Particle settings cause Game Studio to freeze

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#384]
Well I'm not sure if these settings are invalid but it caused Game Studio to freeze.  

How to Repro:

* Open SimpleParticles Demo
* Select "Smoke" entity
* Change Spawners Item 0 so Loop = "Looping, no delay" and Duration X= 0, Y= 0

**Comment by LautrecOfCarim** [comment]
Thanks for the report, it's invalid state, but there wasn't any validation on the engine side.

With the fix the Delay can be no less than 0, and the Duration can be no less than 0.001 (1 millisecond).

**Comment by dfkeenan** [comment]
No worries.

Glad to here it was a simple fix.
