### ISSUE TITLE
Mouse cursor can disappear when using Dragging to change number properties in property grid.

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#385]
Not sure how I managed to do this but I have done it more than once.  Click in number property and drag to increase/decrease value.

I seem to be able to do it if I:
- Move mouse from bellow input field up just until the cursor changes to the four-way arrow.
- Click and quick drag down quickly at the same time

**Comment by manu-silicon** [comment]
This happens whenever you perform a middle or right click on the number property and move the cursor further than the property entry. You can get the cursor back if you manage to left click in one of the editable property entry.
