### ISSUE TITLE
Scripts from other Assemblies than the initial "<ProjectName>.Game" assembly fail to load in scene

### ISSUE THREAD

**Issue by jason-wilmans** [SiliconStudio/xenko#390]
Hi there,

Xenko behaves strangely when trying to use ScriptComponents from assemblies other than the one  created when a new project is started (called <ProjectName>.Game). The problem persists in Xenko 1.7.2.

Steps to reproduce:

1. Start a new Xenko Project with default settings
2. Add a second assembly with "Update Package > Add Code Library". (again default settings)
3. Create a script component that inherits from, e.g. StartupScript (doesn't matter)
4. Try to add the new script component to an entity in the main scene.

In my experience, this already fails with a behavior, where the Game Studio fails to recognize the new script until it is restarted. After that

5. Actually add the (now selectable) new component to an entity in the main scene.
6. Start the scene.

You get following exception on startup:
[exception_details.txt](https://github.com/SiliconStudio/xenko/files/355578/exception_details.txt)

Example GitHub project: https://github.com/jason-wilmans/xenkoMultipleAssemblies.git

**Comment by Kryptos-FR** [comment]
Thanks for the report and the repro project. We will investigate and fix it as soon as possible.

**Comment by Kryptos-FR** [comment]
Found the issue: the code library assembly doesn't get referenced by the platform assembles (e.g. YourGameName.Windows). To fix it manually, open the solution in Visual Studio and add a reference to all your code libraries in the platform projects.

Sorry for the inconvenience, we will fix it an upcoming release.
