### ISSUE TITLE
Mouse and Tap Gesture

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#391]
Hi,
looks like that on my comp (Win10 Pro, standard desktop, no touch monitor) every left mouse click creates Tap Gesture, which is not OK tho.

**Comment by sinkingsugar** [comment]
I'm not quite sure on what API you are using to access that data, but on windows platform actually PointerEvent always is flagged as mouse click, while GestureEvent (which is a more higher level processed event) is all aggregated as a tap , flick, etc ( see GestureType ).
Could you be more specific on what you would expect?

**Comment by EmptyKeys** [comment]
Xenko API ofc. Try this. Open any of your examples and add this

Input.ActivatedGestures.Add(new GestureConfigTap());

somewhere on start of script. Now if you mouse click anywhere while running example, you can see there is Input.GestureEvents for each mouse click. That's imho not good behavior. Mouse clicks should not fire touch gesture events.

**Comment by sinkingsugar** [comment]
This was intended to have gestures from mouse events afaik. We'll discuss it internally. Thanks for your feedback!

**Comment by xen2** [comment]
What we could do is add PointerType info on the gesture to be able to filter them out.

We still want user to have gestures such as flick working with mouse to make it more convenient.

**Comment by EmptyKeys** [comment]
Well you could do it like SunBurn engine does. Just add flag so I can filter "mouse taps" from input, but having both without that info is really weird.
