### ISSUE TITLE
MT Issue

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#396]
Sometime I have weird exception from engine. I guess It could be MT issue related, tho I don't remove model components only changing Enable true or false on it. Could that be a reason for this exception or is that something else?

Exception classes:   
   System.InvalidOperationException
Exception messages:  
   Collection was modified; enumeration operation may not execute.
Stack Traces:        
at System.ThrowHelper.ThrowInvalidOperationException line: 0
at System.Collections.Generic.Dictionary`2+Enumerator.MoveNext line: 0
at SiliconStudio.Xenko.Rendering.ModelRenderProcessor.Draw line: 67
at SiliconStudio.Xenko.Engine.EntityManager.Draw line: 186
at SiliconStudio.Xenko.Engine.Processors.ChildSceneProcessor.Draw line: 79
at SiliconStudio.Xenko.Engine.EntityManager.Draw line: 186
at SiliconStudio.Xenko.Engine.SceneSystem.Draw line: 127
at SiliconStudio.Xenko.Games.GameSystemCollection.Draw line: 125
at SiliconStudio.Xenko.Games.GameBase.Draw line: 790
at SiliconStudio.Xenko.Games.GameBase.DrawFrame line: 986
at SiliconStudio.Xenko.Games.GameBase.TickInternal line: 673
at SiliconStudio.Xenko.Games.GameBase.Tick line: 502
at SiliconStudio.Xenko.Games.GamePlatform.Tick line: 177
at SiliconStudio.Xenko.Games.GamePlatform.OnRunCallback line: 149
at SiliconStudio.Xenko.Games.WindowsMessageLoop.Run line: 231
at SiliconStudio.Xenko.Games.GameWindowWinforms.Run line: 210
at SiliconStudio.Xenko.Games.GameBase.Run line: 463
at EmptyKeys.CoG.CoGApp.Main line: 66

**Comment by xen2** [comment]
How can we reproduce? Does it happen inside a game or editor?

**Comment by EmptyKeys** [comment]
It's in game. I double checked and I think the problem is that I actually do remove entities from scene on the other thread. Is scene thread safe?

**Comment by xen2** [comment]
Sorry for the late answer; no, the entity collection and Children lists are not thread safe.
