### ISSUE TITLE
[1.6.4] "Reload game assemblies and update scripts" reloads project from an invalid path

### ISSUE THREAD

**Issue by discosultan** [SiliconStudio/xenko#397]
How to reproduce:

1. Add a new script in Visual Studio 
2. Switch back to Xenko Studio
3. Hit "Reload game assemblies and update scripts" icon

Tries to reload the game assembly from Xenko's *installation folder* instead of actual *project folder*.

> An exception occurred while compiling the project: Could not find a part of the path **'C:\Program Files\Silicon Studio\Xenko\MyGame2.Game\MyGame2.Game.csproj'**. at System.IO._Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITYATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy) at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver) at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData) at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state) at System.Xml.XmlTextReaderImpl.OpenUrl() at System.Xml.XmlTextReaderImpl.Read() at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath)

**Comment by discosultan** [comment]
The issue is still present in [1.7.0]. This time I added a new script from VS, compiled from VS, switched back to the studio, attached the created script and ran the game.

![ex](https://i.gyazo.com/73fb1ffe93c1342649f6d49b6241a76c.png)

**Comment by sinkingsugar** [comment]
Acually you are creating your game in programs special folders ( they have different permissions under Windows , and other security stuff ) could you try create your game in a normal folder? ( where your user/group is the sole owner )

**Comment by sinkingsugar** [comment]
An nevermind ! I assume your real path was different!

**Comment by discosultan** [comment]
The real project path is 

> C:\Users\j2v\Code\xenko\MyGame5

I can still build the project and successfully run it, so it seems to be related only to scene editor and how it tries to recompile the project when it identifies a new script is added.

**Comment by Benlitz** [comment]
I cannot reproduce this issue. Does it occur all the time for you? Or just the first time? Or randomly?
Also, could you tell me for which platform you are compiling?

**Comment by discosultan** [comment]
@Benlitz 

I'll retry with the latest version. It might have been the first time, because I was simply playing around with new game template/samples. I was compiling for Windows desktop platform.

**Comment by discosultan** [comment]
@Benlitz 

I was also unable to reproduce with version 1.7.6 :+1:  Closing this for now. I'll simply reopen with more detail on how to repro if I ever happen to stumble upon it again.

**Comment by Benlitz** [comment]
Ok, thanks for the update!
