### ISSUE TITLE
MIT, BSD or ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [SiliconStudio/xenko#399]
Is it possible to more away from *GPL license and relicense under one of MIT, BSD or ASL 2.0?

**Comment by xenux** [comment]
Hi sirinath, we are planning to move from the GPL license to a license that allows modification of the engine (without redistribution of the game source code) by end of the year.

**Comment by sirinath** [comment]
Is it possible to consider open sourcing YEBIS and Mizuchi also. If you do this will become the greatest open source Game Engine. Another thing to consider is perhaps joining the Apache Software Foundation which will igve more exposure to the product.

**Comment by sirinath** [comment]
Interested in knowing when the license change will happen.
