### ISSUE TITLE
Issues when adding a reference to another package.

### ISSUE THREAD

**Issue by discosultan** [SiliconStudio/xenko#40]
Hi! 
I've found a couple of issues related to adding a reference to another package. I'm not 100% sure the three cases below are all bugs, but as there is no documentation about the behaviors, I assumed they are and thus decided to share them with you.
- - - -
<b>Symptom:</b> Package will reappear in Paradox Studio solution explorer after being deleted. 
<b>To repro:</b>
1. Create new package from new game template. Let's call it package A.
2. Add a new package to solution from solution explorer. Let's call it package B.
3. Add a reference from package A to package B through solution explorer.
4. Delete package B from solution explorer (Note that reference from package A to B is not removed).
5. Refresh solution explorer by adding a new package or reloading Paradox Studio.
6. Package B is back in the solution explorer.
- - - -
<b>Symptom:</b> Solution will not build after adding a reference to a package which only contains shared library project (which it does by default). 
<b>To repro:</b>
1. Create new package from new game template. Let's call it package A.
2. Add a new package to solution from solution explorer. Let's call it package B.
3. Add a reference from package A to package B through solution explorer.
4. Build the solution. This should fail with 'Unable to find profile [...]'.
- - - -
<b>Symptom:</b> Unable to load asset after adding a reference to a new package. 
<b>To repro:</b>
1. Create new package from new game template. Let's call it package A.
2. Add a new Sprite Font asset called SpriteFont to package A.
3. Open the game code file and add the following line to LoadContent() method.<pre><code>Asset.Load<SpriteFont>("SpriteFont");</code></pre>
4. Launch the game and witness loading asset succeed.
5. Add a new package to solution from solution explorer. Let's call it package B.
6. Add a reference from package A to package B through solution explorer.
7. Modify package B .pdxpkg file and add a platform specific profile (in order to successfully build the solution).
8. Launch the game and witness loading the same asset fail with 'Asset not found'.

**Comment by Kryptos-FR** [comment]
First issue (package dependencies) has been fixed in 1.5-beta version (December release).
I cannot reproduce the two other issues, I suppose they also have been fixed.

**Comment by discosultan** [comment]
Thanks! I haven't retested the other two issues, but I'll close this case for now - a lot has changed since it was reported and it's probably wiser to create a new issue if needed.
