### ISSUE TITLE
Xenko 1.6.5 crash 

### ISSUE THREAD

**Issue by Lavistios** [SiliconStudio/xenko#406]
Hi, 
For a moment now, I have a problem with Xenko 1.6.5. I have asked to the Xenko account on Twitter and they said to open an issue here..
I think the problem is from my computer but when I create a New Project, the console appears and when the editor is loading, my screen turns black and then Xenko crash
Please take a look at the images below
Thank you.
( Sorry for mistakes, I'm French)

New Project.
![sxs](https://cloud.githubusercontent.com/assets/19571535/15540464/c5926b3c-2287-11e6-8e11-5134aee8effe.png)

He has crashed.
![011](https://cloud.githubusercontent.com/assets/19571535/15540468/ce23766a-2287-11e6-85c2-8ef948c310d5.png)

**Comment by Kryptos-FR** [comment]
That is unfortunate. What's more is that even the crash report doesn't seem to appear, right?

Some questions first to try to understand your issue:

- Are you sure that all the pre-requisites were properly installed along Xenko? If you are not sure, try reinstalling Xenko. The installer should tell you about the pre-requisites.

- Do you have an antivirus that might prevent Xenko from running? If so, try adding Xenko as an exception or disable momentarily your antivirus/firewall.

- Finally, does it happen only for version 1.6.5, or do you have the same issue with previous versions as well?

**Comment by YotPhiligan** [comment]
Hi, have the same issue. In some cases editor crushed after launching and can not send crash report.

Sorry for my english.

**Comment by Lavistios** [comment]
Hello

I found the problem

When Xenko loads a big scene, my Nvidia display driver doesn't support and crash. When everything returns to normal, Xenko crash.

My solution is to load empty scenes ("Hello World project" for example) as my driver will crash not and everything works perfectly



Otherwise I have a question, I'll open a topic but how do you remove the mipmap applied on sprites. When I put everything on 32 bit and I Unchecks the box mipmap, there is always a mipmap applied, I mean on Unity we can clearly see the pixels in the image with dot as a filter but not on Xenko

It is rather unfortunate.



Sorry for the mistakes even once ^^

**Comment by Benlitz** [comment]
Hi!

You could try to update your NVidia drivers. I'm closing this issue for the moment since it seems related to your specific configuration. Feel free to re-open or create a new one if you still have issues with up-to-date drivers.
