### ISSUE TITLE
Prefabs, scale and particles v1.6.6b

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#407]
Hi, 
In version 1.6.6b all prefabs are acting weird in game or in editor, randomly changing scale for one frame and then back to correct value.

**Comment by EmptyKeys** [comment]
Think it has something to do with Particle fix in latest update. They are all over the place now, randomly changing position and scale.

**Comment by xen2** [comment]
Thanks for the report, will try to repro.

Just in case, do you happen to know:
- Does it affect only particles or everything?
- Is it only for 1 frame or multiple frames?
- Is it editor only or when running the game as well?

**Comment by EmptyKeys** [comment]
Particles are the most visible issue. They jump to other position and back. From time to time even the model change scale. I would say its max X frames. It's very quick.

Both in editor and in game.

Short video here - http://emptykeys.com/uploads/XenkoIssue.wmv

**Comment by LautrecOfCarim** [comment]
Hi,
I tried to reproduce it, but the rendering on my side is stable for both the main view and the asset view. Could you send us the prefab files (.xkprefab) related to the issue? Could my test assets are too simple and can't show the bug. No need for the actual models or textures.

**Comment by EmptyKeys** [comment]
Sure, try this one http://emptykeys.com/uploads/unit_prefab.zip

**Comment by LautrecOfCarim** [comment]
Thanks for the data, I think I found it. It is indeed the particles fix, and it only triggers if you have 8 or more particle systems on the same hierarchy and they trigger transform component updates concurrently. Sorry I've missed this case, I'll make a test for it.

If you work with source here is a patch:
[0001-Particles-Bug-fix-where-2-or-more-child-entities-con.zip](https://github.com/SiliconStudio/xenko/files/290221/0001-Particles-Bug-fix-where-2-or-more-child-entities-con.zip)

**Comment by EmptyKeys** [comment]
np, thanks for the fix

**Comment by xen2** [comment]
Fixed in 1.6.7!
