### ISSUE TITLE
Mipmap in Sprites

### ISSUE THREAD

**Issue by Lavistios** [SiliconStudio/xenko#409]
Hello

When I add an image in xenko, I put the format 32-bit I Unchecks the box mipmap, it seems that there is always a mipmap applied to the sprite... I mean on Unity with the point filter, the mipmap is not applied and you can clearly see the pixels, but it is not the same result on Xenko

Do you have a solution for this?

please, look at the images below.

Thank you

![01](https://cloud.githubusercontent.com/assets/19571535/15629424/e8ca4014-2518-11e6-81c8-ff8ba60b097c.png)

Sorry again for errors in English...

**Comment by Kryptos-FR** [comment]
Did you check if any antialiasing effect was still applied to your scene?

Especially FXAA as it is executed on the final pixels (not calculated from actual geometry). Therefore it will also apply antialiasing inside textures. You should consider disabling it,especially if you want a pixelated look for your game.

To disable it, go to the *Graphics Composition* settings of your scene. Then Master -> Renderers -> Effects -> Antialiasing. Then either uncheck the effect or select *None* from the combobox of the *Type* property.

**Comment by sinkingsugar** [comment]
Like you deducted from your post the issue seems the sampler ( or point filter ), with the new pipeline I'm not sure how you are supposed to set it. Are you rendering with a custom renderer or sprite batch?

**Comment by Lavistios** [comment]
Hello

Thanks for all your answers, I do not know if I did something is wrong but it would seem that I do not have the tab "Effects-> Antialiasing"
![01](https://cloud.githubusercontent.com/assets/19571535/15654559/946520b0-2695-11e6-9e64-7c358a370a23.png)

**Comment by sinkingsugar** [comment]
It's totally fine, you are not using any post effects / layers.

**Comment by jwollen** [comment]
Sprites are currently always drawn with linear filtering, even if `Generate mipmaps` is false (Resulting in aliasing)

We will consider adding a way to make sprites pixel-perfect. Thanks for the feedback!

**Comment by Lavistios** [comment]
Thanks, I await the corresponding update with impatience ! !

**Comment by LautrecOfCarim** [comment]
Hi @Lavistios 

I'm closing the other issue because they duplicate each other and this one is still open.

Could you share the data you are using so we can test it internally? If it's a single texture that you want to render with Point (Nearest) sampler it's probably a very easy fix. The SpriteBatch currently uses linear sampling for all sprites, I assume being able to choose point sampler will work for you.

Otherwise pixel-perfect rendering for sprites is a little more complicated, but I have the feeling it might not be required for your case.

**Comment by Lavistios** [comment]
Hi @LautrecOfCarim 

Thanks for your reply, I want to just render a single image with "Point (Nearest) sampler" so that it looks like most of the "Pixelated" games. If it is impossible for the moment, it's ok, I'll just extend my images or recreates them.

Here are the images in question:

https://drive.google.com/folderview?id=0B4ipeKZwsisLc0NxcnhncWtLams&usp=sharing

**Comment by LautrecOfCarim** [comment]
Exposing the filtering is a simple issue, I hope it is enough for your case. Check it in the next update (should be out with 1.7.6 I think). It will appear in the Sprite Component attributes (not on the Texture side).

![texturefiltering](https://cloud.githubusercontent.com/assets/8448895/17044093/aa0700ec-4ff7-11e6-81d8-ca7ec27fba7f.png)
