### ISSUE TITLE
SiliconStudio.Core.Mathematics.Color cannot be serialized

### ISSUE THREAD

**Issue by angstr0m** [SiliconStudio/xenko#411]
An AsyncScript with a public property:
`public Color MyColor = Color.Blue;`
Will result in an error that states that the component cannot be loaded in the Xenko editor.

A public property with Color4 works as expected:
`public Color4 MyColor = Color.Blue;`

**Comment by xen2** [comment]
Good point, we'll fix that one!

**Comment by Kryptos-FR** [comment]
I cannot reproduce this.

@angstr0m Which version of Xenko are you using? Does it happen on your side with an empty script that just contains this property? Compilation issues and having some non-serializable properties can prevent a script to be loadable.

**Comment by angstr0m** [comment]
Thanks for looking into it.

I'm using Xenko 1.6.7-beta. After a restart of the system (without changing the code or recompiling) the error seems to be gone. An empty script with just the color seems to be working. Before the restart, the described behaviour could be reliably reproduced.

The solution compiled without errors in Visual Studio 2015 when the error occured. At the time the color property was the only public member on that class.

I'll keep an eye on it and let you know if I find a way to reproduce the error reliably (this time on different computers and after a restart).

This issue can be closed. Again thanks for the help.

**Comment by Kryptos-FR** [comment]
It is possible than one of the services that are started along the Game Studio was not correctly restarted (or crashed) when you upgraded to 1.6.7 (which would explain why a system restart seemed to fix it).

Thank you for the report anyway. If this issue occurs again, feel free to reopen (hopefully with more details on how to reproduce).
