### ISSUE TITLE
Exception with Depth of Field

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#419]
Hi,
every time I change resolution to 1920x1080 game eats all memory. Problem is exception, which is not raised so game does not crash, but keeps running. Stack trace is bellow.

Looks like the culprit is Depth of field post-process effect. If I turn that off, problem is gone. Here are the settings, which I use:

Size 0.1, DOF Areas 0, 0.2, 0.26, 1, QP 0.5, Technique HTR, Auto Focus false

`SiliconStudio.Xenko.dll!SiliconStudio.Xenko.Rendering.ParameterCollection.Set<SiliconStudio.Core.Mathematics.Vector2>(SiliconStudio.Xenko.Rendering.ValueParameter<SiliconStudio.Core.Mathematics.Vector2> parameter, int count, ref SiliconStudio.Core.Mathematics.Vector2 firstValue) Line 359	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Images.CoCMapBlur.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 87	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Images.DepthOfField.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 430	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Images.PostProcessingEffects.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 269	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.SceneEffectRenderer.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context, SiliconStudio.Xenko.Rendering.RenderFrame output) Line 87	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.SceneRendererBase.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 98	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.GraphicsRendererCollectionBase<SiliconStudio.Xenko.Rendering.ISceneRenderer>.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 162	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Composers.SceneGraphicsLayer.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 146	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Composers.PipelineCompositorLayers.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 57	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Composers.SceneGraphicsCompositorLayers.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Engine.SceneInstance.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context, SiliconStudio.Xenko.Rendering.RenderFrame toFrame, SiliconStudio.Xenko.Rendering.Composers.ISceneGraphicsCompositor compositorOverride) Line 180	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.SceneRendererBase.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 98	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.GraphicsRendererCollectionBase<SiliconStudio.Xenko.Rendering.ISceneRenderer>.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 162	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Composers.SceneGraphicsLayer.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 146	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Composers.PipelineCompositorLayers.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 57	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.Composers.SceneGraphicsCompositorLayers.DrawCore(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Rendering.RendererBase.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context) Line 48	C#
 	SiliconStudio.Xenko.Engine.dll!SiliconStudio.Xenko.Engine.SceneInstance.Draw(SiliconStudio.Xenko.Rendering.RenderDrawContext context, SiliconStudio.Xenko.Rendering.RenderFrame toFrame, SiliconStudio.Xenko.Rendering.Composers.ISceneGraphicsCompositor compositorOverride) Line 180	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GameSystemCollection.Draw(SiliconStudio.Xenko.Games.GameTime gameTime) Line 125	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GameBase.Draw(SiliconStudio.Xenko.Games.GameTime gameTime) Line 790	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GameBase.DrawFrame() Line 986	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GameBase.TickInternal() Line 655	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GameBase.Tick() Line 502	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GamePlatform.Tick() Line 177	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GamePlatform.OnRunCallback() Line 149	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.WindowsMessageLoop.Run(System.Windows.Forms.Control form, SiliconStudio.Xenko.Games.WindowsMessageLoop.RenderCallback renderCallback, bool useApplicationDoEvents) Line 231	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GameWindowWinforms.Run() Line 210	C#
 	SiliconStudio.Xenko.Games.dll!SiliconStudio.Xenko.Games.GameBase.Run(SiliconStudio.Xenko.Games.GameContext gameContext) Line 463	C#
`

**Comment by EmptyKeys** [comment]
will test this in 1.7 asap :)

**Comment by xen2** [comment]
Thanks for the report.
This has been fixed in 1.7 with ab3553adbedbe99ca8bf3eaf38b49bfe67bb14e9

**Comment by EmptyKeys** [comment]
nah, i will move to 1.7
