### ISSUE TITLE
[1.7.0] AudioEngine.cs not found

### ISSUE THREAD

**Issue by discosultan** [SiliconStudio/xenko#420]
- Xenko 1.7.0
- Windows 7 x64
- VS 2015
- Default project settings

---

Creating any new game/sample and running it for the first time from Visual Studio opens the following dialog:

![AudioEngine.cs](https://i.gyazo.com/deb52e63cc4d40a1bfcbf8c89ac624ed.png)

Hitting cancel will throw:

![SEHException](https://i.gyazo.com/7851163723bd81fce7c657b5f8db851c.png)

Any consecutive run will no longer prompt the dialog but simply throw:

![AccessViolationException](https://i.gyazo.com/099fb354308f166917f65c72e118edfc.png)

**Comment by sinkingsugar** [comment]
Do you have directx June 2010 runtime installed on that machine? Pretty much a requirement if it's Windows 7.

**Comment by discosultan** [comment]
@sinkingsugar  I can double check on Monday. Previous versions of Xenko were running fine.

**Comment by sinkingsugar** [comment]
Should be a requirement already, will have to check.
On Windows 8+ XAudio2 is part of the OS.

**Comment by sinkingsugar** [comment]
Found the issue, happens only on 32bit. I already fixed it internally.

**Comment by discosultan** [comment]
@sinkingsugar  That is great news! And yes, I did have the entire DX June 2010 SDK installed.
