### ISSUE TITLE
"Curve" dropdown lists in property grid always show "(None)"

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#421]

**Comment by LautrecOfCarim** [comment]
Which property is this? I couldn't find any which is broken (cannot be assigned), but many of them have initial value of (None).

We have curves mainly in particles I think, and some of them have a default curve when you first create them, some of them are (None) by default, but can be assigned later from the dropdown list.

**Comment by dfkeenan** [comment]
The Curve property of particle updaters always seems to say none:

![image](https://cloud.githubusercontent.com/assets/6070165/16576798/c900ca80-42d4-11e6-9e47-175473277319.png)

If you press the little blue down arrow than it does have the selected item highlighted (default is "Animation"). You just can't tell what is selected without pressing the dropdown.

1.7.1 update didn't change this.  I added a new entity to scene with a new particle component setup. Not sure if creating a whole to project would change anything.

**Comment by LautrecOfCarim** [comment]
So it was a different issue, we are hiding the keyframes of the curves from the property grid as they can be quite many, but were preventing the other child properties from displaying either. It's fixed internally, should be out with the next patch.

![animationcurve](https://cloud.githubusercontent.com/assets/8448895/16580485/b110d518-42df-11e6-8b1c-cbf3c65dfc41.png)

**Comment by dfkeenan** [comment]
Cool!
