### ISSUE TITLE
Rotation animation particle updater or does not work unless you have a Size initializer.

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#425]
The update method checks for the size field rather than the rotation one:
https://github.com/SiliconStudio/xenko/blob/974711164d2c45c66bc7cd3725fe2b637dff6824/sources/engine/SiliconStudio.Xenko.Particles/Updaters/UpdaterRotationOverTime.cs#L71

**Comment by LautrecOfCarim** [comment]
Thanks for the report, I updated the code on our side.

**Comment by dfkeenan** [comment]
Your welcome.

You have to like the simple fixes :smile:
