### ISSUE TITLE
[1.7.0] Silent crash after adding code library

### ISSUE THREAD

**Issue by YotPhiligan** [SiliconStudio/xenko#426]
After adding code library or adding additional platform editor silently crash. Then if launch again project not build properly

**Comment by sinkingsugar** [comment]
Additional platform seems to work but I'm seeing issues for code library. We will investigate. Thanks for the report!

**Comment by sinkingsugar** [comment]
Actually the additional library was just not building properly the first time, no crash. Further times worked just fine.
Could you add more info about the crash?
Also could you repeat the same steps on a default sample or a `New Game`?
Thank you!

**Comment by YotPhiligan** [comment]
I tried to replicate the problem on another machine it seems the problem occurs only on my home computer. Maybe just a local problem with the Win10 insider preview build need to check.
Sorry for the inconvenience.

**Comment by sinkingsugar** [comment]
Ok thanks, I'm closing this issue for now. We will improve the workflow anyway because at the moment adding a Library to a project from the editor it won't load any scripts from the new library unless the game studio is restarted or the project is reloaded.
