### ISSUE TITLE
Android Development broken in 1.7.0

### ISSUE THREAD

**Issue by jaladaGmbH** [SiliconStudio/xenko#427]
Create a new Space Escape project or any other example and build it for Android, you get the following exception:
07-02 20:36:56.060 D/MALI    ( 6931): #define samplerBuffer sampler2D
07-02 20:36:56.060 D/MALI    ( 6931): #define isamplerBuffer isampler2D
07-02 20:36:56.060 D/MALI    ( 6931): #define usamplerBuffer usampler2D
07-02 20:36:56.060 D/MALI    ( 6931): #define texelFetchBuffer(sampler, P) texelFetch(sampler, ivec2((P) & 0xFFF, (P) >> 12), 0)
07-02 20:36:56.060 D/MALI    ( 6931): 
07-02 20:36:56.060 D/MALI    ( 6931): const int TMaxLightCount_id91 = 1;
07-02 20:36:56.060 D/MALI    ( 6931): const float PI_id101 = 3.14159265358979323846;
07-02 20:36:56.060 D/MALI    ( 6931): struct PS_STREAMS 
07-02 20:36:56.060 D/MALI    ( 6931): {
07-02 20:36:56.060 D/MALI    ( 6931):     vec3 normalWS_id16;
07-02 20:36:56.060 D/MALI    ( 6931):     vec4 PositionWS_id19;
07-02 20:36:56.060 D/MALI    ( 6931):     vec2 TexCoord_id96;
07-02 20:36:56.060 D/MALI    ( 6931):     float FogFactor_id88;
07-02 20:36:56.060 D/MALI    ( 6931):     vec3 viewWS_id61;
07-02 20:36:56.060 D/MALI    ( 6931):     vec3 shadingColor_id66;
07-02 20:36:56.060 D/MALI    ( 6931):     float matBlend_id37;
07-02 20:36:56.060 D/MALI    ( 6931):     vec3 matNormal_id45;
07-02 20:36:56.060 D/MALI    ( 6931):     vec4 matColorBase_id46;
07-02 20:36:56.060 D/MALI    ( 6931):     vec4 matDiffuse_id47;
07-02 20:36:56.060 D/MALI    ( 6931):     vec3 matDiffuseVisible_id62;
07-02 20:36:56.060 D/MALI    ( 6931):     vec3 matSpecular_id49;
07-02 20:36:56.060 D/MALI    ( 6931):     vec3 matSpecularVisible_id64;
07-02 20:36:56.060 D/MALI    ( 6931):     float matSpecularIntensity_id50;
07-02 20:36:56.060 D/MALI    ( 6931):     float matGlossiness_id48;
07-02 20:36:56.060 D/MALI    ( 6931):     float alphaRoughness_id63;
07-02 20:36:56.060 D/MALI    ( 6931):     float matAmbientOcclusion_id51;
07-02 20:36:56.060 D/MALI    ( 6931):     float matAmbientOcclusionDirectLightingFactor_id52;
07-02 20:36:56.060 D/MALI    ( 6931):     float matCavity_id53;
07-02 20:36:56.060 D/MALI    ( 6931):     float matCavityDiffuse_id54;
07-02 20:36:56.066 E/Xenko   ( 6931): [SceneInstance]: Error: An exception occurred while rendering. System.InvalidOperationException: Error while compiling GLSL shader. [0:10: S0032: no default precision defined for variable 'PI_id101'
07-02 20:36:56.066 E/Xenko   ( 6931): ]

**Comment by xen2** [comment]
Thanks for the report.
We will need to take another look at the GLSL shader specifications, might have missed something (or it's a Mali GPU specific issue)

What phone, OS version (and exact GPU if you know) is it?

**Comment by jaladaGmbH** [comment]
The tablet is called ARCHOS 70b Helium 4G with Android 5.1 / Mali 720 MP1
[Technical Spec](http://www.archos.com/en/products/tablets/helium/archos_70bhelium/specs.html?#menu)

**Comment by jwollen** [comment]
This is fixed internally and will be included in the upcoming bugfix release.
