### ISSUE TITLE
[1.7.0] zlib1.dll missing

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#428]
Zlib1.dll is not in directory with msdfgen, so new font types are not working.

**Comment by LautrecOfCarim** [comment]
Thanks for the report!

We recompiled msdfgen with a static freetype library so it won't use zlib1.dll or freetype6.dll anymore, but can you tell me which fonts failed to compile so I can confirm they work properly now?

**Comment by EmptyKeys** [comment]
Well zlib1.dll file was missing so any font had a problem to compile.

**Comment by sinkingsugar** [comment]
We tested only with uncompressed fonts apparently :)
Anyway should be fixed in the next release.
