### ISSUE TITLE
SDF fonts

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#429]
Hi,
something is still wrong with new font type. I can create and compile it, but it does look weird in game studio or in game. Do I have to set something special? I'm on Windows 10, game running on DX11, LDR and Gamma color space.

![sdf_bug](https://cloud.githubusercontent.com/assets/7707327/16582950/8e04df9c-42b2-11e6-8f98-dcbbf44d71b4.png)

**Comment by Kryptos-FR** [comment]
Signed distance field fonts need a shader to be rendered properly and the preview currently doesn't support shaders. So what you are seeing is the underlying generated texture (see http://doc.xenko.com/latest/manual/ui/sprite-fonts.html#signed-distance-field).

If you are seing some artefacts (like tiny holes) when using a large text size, try increasing the font size (20 by default). It should look sharper but will use more texture space.

**Comment by EmptyKeys** [comment]
I see. I want to make support for that font type in my UI. How can I draw it with sprite batch?

**Comment by LautrecOfCarim** [comment]
Hi,

Sorry about the Preview, I must have overlooked it, will fix it shortly.

About the shaders, you will need a custom effect to draw the SDF fonts with the SpriteBatch/UIBatch. In the Begin method of BatchBase one of the attributes is an effect instance override. 

To build the effect you can inherit from ![SignedDistanceFieldFont](https://github.com/SiliconStudio/xenko/blob/master/sources/engine/SiliconStudio.Xenko.Graphics/Shaders/SignedDistanceFieldFont.xksl)
and call float4 FontColor(float4 sampledColor, float4 textColor, float4 borderColor, float borderThickness) to get the correct pixel color from a sampled value. Or you can write your own implementation. We use a fork of ![msdfgen](https://github.com/SiliconStudio/msdfgen) to build the atlas textures, there is also a short example of the shaders.

**Comment by EmptyKeys** [comment]
perfect, it's working (with the help of custom effect sample) including border :)

**Comment by LautrecOfCarim** [comment]
Nice to hear that!
I fixed the Asset Preview issue internally, should be out with the next update.
