### ISSUE TITLE
Create collider shape at runtime

### ISSUE THREAD

**Issue by YotPhiligan** [SiliconStudio/xenko#432]
I try to create shape like this:
![default](https://cloud.githubusercontent.com/assets/6679239/16707830/e9333e72-45f5-11e6-9ec8-891ed3ee35a9.PNG)
But actually it doesn't work.
PhysicsColliderShape contain the CreateShape method that I think does what I want but it is marked as internal so I can not use it in my code.
Would be nice if we could create shape at runtime. 

Thanks.

**Comment by sinkingsugar** [comment]
As I've already answered in the Xenko Answer page. 
This is not possible with convex hull collider shapes because they are computed at build time. And so they have to be created with the game studio.
Other kind of shapes are fine tho.
For example to create and use a compound shape:
```
var entity = new Entity();
var box1 = new BoxColliderShapeDesc {Size = new Vector3(0.5f, 0.5f, 0.5f)}; //add offset etc
var box2 = new BoxColliderShapeDesc {Size = new Vector3(0.5f, 0.4f, 0.5f)}; //add offset etc
var box3 = new BoxColliderShapeDesc {Size = new Vector3(0.5f, 0.5f, 0.3f)}; //add offset etc
var rigidBody = Entity.GetOrCreate<RigidbodyComponent>();
rigidBody.ColliderShapes.Add(box1);
rigidBody.ColliderShapes.Add(box2);
rigidBody.ColliderShapes.Add(box3);
SceneSystem.SceneInstance.Scene.Entities.Add(entity); //this is important! the entity must be added to the scene after the shapes have been added to the rigidBody
```

**Comment by sinkingsugar** [comment]
That said. We might in the future allow complex assets to be built at runtime. but not in the short term.

**Comment by YotPhiligan** [comment]
Great! Thank you for your time.
