### ISSUE TITLE
VS12 crashes when I want to show file list

### ISSUE THREAD

**Issue by na2axl** [SiliconStudio/xenko#434]
When I launch VS12 with Xenko, the VS12 window appear normally and I can use it without promblem. But when I want to unfold the ProjectName.Game project or the ProjectName.Windows project VS12 automatically crashes and ask me to restart it! I'm working with Windows 10, VS12 Update 5 and Xenko 1.7.1-beta.

**Comment by Benlitz** [comment]
Hi!

Sorry, I cannot reproduce your issue. Would you mind to give us a bit more information?
* Do you have the Xenko plugin for Visual Studio installed?
* Just to be sure: you're mentionning VS12, you mean Visual Studio 2012 or Visual Studio 12 (which is Visual Studio 2013)?
* Do you have any other version of Visual Studio currently installed?
* Does your project contains any custom effect (xksl files)?
* In which folder of your computer did you install Xenko?

**Comment by na2axl** [comment]
Hi,

- I have the Xenko plugin for Visual Studio installed
- I'm using Visual Studio 2012 Ultimate Update 5
- I've not other version of Visual Studio installed
- No, my project doesn't contains custom effect
- Xenko is installed in "C:\Program Files\Silicon Studio\Xenko" (x64 program files folder)

**Comment by na2axl** [comment]
Hi,

I've recently update Xenko to 1.7.4-beta version and this have solve my problem! Maybe the past version have some bugs or it was not properly installed in my pc... But I can use Xenko again :-).
