### ISSUE TITLE
An error when I build xenko

### ISSUE THREAD

**Issue by QuinShuai** [SiliconStudio/xenko#439]
How to build xenko engine? An error when according to Build Instructions.
![qq 20160727115949](https://cloud.githubusercontent.com/assets/7962273/17163424/bed874e4-53f1-11e6-97c5-3db42b0d0a14.png)

**Comment by xen2** [comment]
It looks like git lfs didn't work properly.

Please make sure that you installed it (https://git-lfs.github.com/)
Also, you have to clone with `git **lfs** clone` (or run `git lfs fetch` after a non lfs `git clone`)

Hope that fixes your problem.

**Comment by QuinShuai** [comment]
Thanks for helping me out. This issue has been resolved.
