### ISSUE TITLE
Crash on project load, when installed on non C-drive on versions 1.6+:  "AssemblyProcessorTask" 

### ISSUE THREAD

**Issue by Godsfoot** [SiliconStudio/xenko#450]
I had originally installed Xenko version 1.5 on my M drive to conserve space on my primary C drive.

Everything worked fine using this install location. I then upgraded my project to 1.6 and 1.7 on separate occasions and the same error appeared on launching the editor and attempting to build and deploy my projects.

```
[M:\Program Files (x86)\Xenko\GamePackages\Xenko.1.7.9-beta\Targets\Xenko.targets(172,5)]: Error: The "AssemblyProcessorTask" task could not be loaded from the assembly M:\Program Files %28x86%29\Xenko\GamePackages\Xenko.1.7.9-beta\deps\AssemblyProcessor\SiliconStudio.AssemblyProcessor.exe. Could not load file or assembly 'file:///M:\Program Files %28x86%29\Xenko\GamePackages\Xenko.1.7.9-beta\deps\AssemblyProcessor\SiliconStudio.AssemblyProcessor.exe' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
[]: Error: Unable to build assembly reference [M:\Users\<USERNAME>\Documents\Xenko Projects\MyGame\MyGame\Bin\Windows\Debug\MyGame.Game.dll]
```

I Googled looking for an answer and found this discussion:
[http://www.gitterforum.com/discussion/siliconstudio-paradox?page=82]

After following the conversation between Devs and a user named Anon, I was able to reinstall Xenko in my primary disk and continue developing. I would prefer to be able to install the latest version on another drive, considering my primary is a rather small SSD. Hopefully this will be resolved soon.

Thanks for the amazing product!

**Comment by Kryptos-FR** [comment]
There were some issues with long path name (see for examplwe https://github.com/SiliconStudio/xenko/issues/410) with versions prior to 1.6.7-beta. Also your path includes "Program Files (x86)" which seems to be incorrect since Xenko is 64bit.

Could you try to install Xenko again with the latest installer (https://xenko.com/download/) on your M: drive and tell us if it works?

**Comment by Godsfoot** [comment]
Thanks for the info. I was able to reinstall from the 1.8 launcher onto my M: drive and it appears build fine now.

**Comment by xen2** [comment]
Great, closing then! :smile:
