### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Scellow** [SiliconStudio/xenko#451]
Hello

This simple scene takes up to 16% CPU usage, and if i add the tiles in the ground it takes up to 34%

The same scene (with tiles) takes only 7% in both libGDX and Urho3D(c# binding)

I believe there is something wrong

I disabled every effects possible, but still high CPU usage

![theroguerxenko vshost_2016-08-28_19-53-18](https://cloud.githubusercontent.com/assets/4980894/18036428/304f3edc-6d6a-11e6-915f-b42566a88b3c.png)

**Comment by thinkpadder1** [comment]
Unless you upload the project for us to test, we can't really help.

**Comment by Scellow** [comment]
I'll send you a test project to replicate the issue once i come back to home, i'm closing this for the moment

**Comment by Kryptos-FR** [comment]
How many entities in your scene?
