### ISSUE TITLE
Studio issues

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/xenko#454]
![error](https://cloud.githubusercontent.com/assets/10830201/18199193/f0180e4c-7107-11e6-8be9-74cb90501dcd.png)

**Comment by Kryptos-FR** [comment]
Thanks for the report.
Could you give us more details? For example your machine configuration (OS, CPU, GPU), screen(s) resolution(s)...

**Comment by Zulusas** [comment]
Windows 7 64b; 
Processor	Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz, 2801 Mhz, 2 Core(s), 4 Logical Processor(s);
NVIDIA GeForce GT 525M;
1920x1080.

**Comment by Kryptos-FR** [comment]
Maybe related to pixel density. Could you try to set it to 100 % and see if the issue remains?

**Comment by Zulusas** [comment]
It's related to pixel density. No issue with 100%. My pixel dansity 125%.

**Comment by makotech222** [comment]
Same problem for me. DPI is also > 100% on my monitor.

**Comment by kobush** [comment]
Same on my machine with higher DPI setting. It works fine in 1.7 version.

**Comment by L3tum** [comment]
Hey, didn't want to add another issue, but I have the same problem and I tried to change the DPI to 100% and the scene editor is still "misaligned" like in the screenshot OP posted. The DPI didn't change it at all, it was always misaligned. Plus, I got a fairly big screen so I would appreciate if the solution wouldn't be to set the DPI down^^

**Comment by manu-silicon** [comment]
@L3tum In the meantime you can always do the way around and pretend that GameStudio is high DPI aware:
https://github.com/SiliconStudio/xenko/issues/470#issuecomment-256172622

**Comment by L3tum** [comment]
@manu-silicon Thanks for pointing it out! Unfortunately I currently have a rather large screen and no possibility to switch it to a smaller screen, so smaller icons would make it unusable for me.
