### ISSUE TITLE
Some of the samples seem to be broken for 1.8

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#456]
I have 1.7 and 1.8 installed. if you create a new project from a sample it opens in GS 1.8. If you close GS and reopen launcher says they are 1.7 if you open them it opens GS 1.7 and has errors loading project.  I got the same result with the samples Animated PRoperties and Render Scene To Texture.  Not sure how many projects it affects.   New blank game seems to be ok though.

**Comment by EmptyKeys** [comment]
Problem is that version inside package files is not updated. I had to manual rewrite that number.

**Comment by Kryptos-FR** [comment]
It is fixed internally and will be in the next release. Sorry for the inconvenience.
