### ISSUE TITLE
Scripts under GPL v3

### ISSUE THREAD

**Issue by EternalTamago** [SiliconStudio/xenko#457]
Hello.

BasicCameraController
EventDispatcher
FpsCamera
PrefabInstance

It seems that these scripts are under GPL v3.(from descriptions in the head of the file)
Specially the BasicCameraController is included to New Game by default.
Is this no problem to binary license users?

Sorry for my poor English.

Xenko 1.8.0-beta / Launcher 1.5.3
Visual Studio Community 2015 Update 3
Windows10 Pro x64

**Comment by Kryptos-FR** [comment]
Good catch. Those scripts should not be under GPL.

Will be fixed in the next release.

**Comment by EternalTamago** [comment]
Thank you very much!
