### ISSUE TITLE
CharacterComponent.Jump() doesn't jump properly

### ISSUE THREAD

**Issue by EternalTamago** [SiliconStudio/xenko#460]
Hello.

The CharacterComponent.Jump() doesn't jump properly after some jumps.
Or the jumper disappears somewhere by the first jump running in the Visual Studio.

[steps to reproduce]
1. Create the Physics Sample project.
2. Play it and switch the scene to the character controller scene in game.
3. Jump several times by pressing the space key.

Or that is similar in the following simple project.

- Create a New Game project.
- Add a SyncScript as TestScript.
- For the Ground entity.
	+ Add a StaticColliderComponent.
	+ Add that collider shape as a inifite plane(x=0, y=1, z=0).
- For the Sphere entity.
	+ Add a CharacterComponent.
	+ Add that collider shape as a sphere.
	+ Add a TestScript.

```csharp
// [TestScript.cs]
using SiliconStudio.Xenko.Input;
using SiliconStudio.Xenko.Engine;
using SiliconStudio.Xenko.Physics;

namespace MyGame
{
    public class TestScript : SyncScript
    {
        private CharacterComponent character__;
        public override void Start()
        {
            character__ = Entity.Get<CharacterComponent>();
        }
        public override void Update()
        {
            if (Input.IsKeyPressed(Keys.Space))
            {
                character__.Jump();
            }
        }
    }
}
```

Thanks!

Xenko 1.8.1-beta / Launcher 1.5.3
Visual Studio Community 2015 Update 3
Windows 10 Pro x64

**Comment by LautrecOfCarim** [comment]
Hi @EternalTamago ,

Thanks for the report. There was a mismatch between the wrapper and the new Bullet library (Jump now takes a Vector3 as input) which caused some crashes or NaN results. It has been fixed internally and will be out with the next patch!

**Comment by EternalTamago** [comment]
Hi @LautrecOfCarim ,
Great! I look forward to the next patch.
Thank you very much!
