### ISSUE TITLE
CharacterController resets rotation to 0 each frame

### ISSUE THREAD

**Issue by KLNHOMEALONE** [SiliconStudio/xenko#461]
While thinking it all over a bit, I strongly believe that this is a bug in Character Controller or in bullet library.
Why is it required to rotate entity every frame?
The workflow should be like something:
 1. Rotate the entity once on a desired angle
 2. Update physics transformation once.
 3. Move it.
 4. While moving it should keep the given direction and rotation

But now the entity rotation is reset every frame to 0.
This is weird.

**Comment by KLNHOMEALONE** [comment]
look the whole discussion here [](http://answers.xenko.com/questions/571/how-do-you-use-the-charactercontroller-in-3d.html#answer-2182)

**Comment by KLNHOMEALONE** [comment]
Look here please
[here](http://answers.xenko.com/questions/571/how-do-you-use-the-charactercontroller-in-3d.html#answer-2182)

**Comment by sinkingsugar** [comment]
There is a new property in the CharacterController called Orientation , please use that to set the rotation from now.
Still your movement vector is the one that must provide both speed and direction multiplied by simulation fixed delta.

**Comment by KLNHOMEALONE** [comment]
> Still your movement vector is the one that must provide both speed and direction multiplied by simulation fixed delta.
Yeah, that's right. This mean that there's no need to rotate entity every frame to face the destination. It should be done by character controller. The bug is that instead of facing the destination point the character is facing Vector3.Zero each frame.

**Comment by sinkingsugar** [comment]
Yes please try using Orientation property directly from the character component and that should do the trick.

**Comment by KLNHOMEALONE** [comment]
Looks like it can be closed
