### ISSUE TITLE
Xenko Won't start. PLEASE HELP!!

### ISSUE THREAD

**Issue by RealAquilus** [SiliconStudio/xenko#463]
My specs are:
Windows 7 professional x64
I7 4790k
R9 270x Toxic
16gb ddr3 1600mhz
Visual studio 2013 update 5 
(With visual c++ redistributable 2005, 2008,2010,2012,2013.2015 all in both version x86 and x64)
In have installed xenko in my second drive "F:\Program Files\Xenko"
.Net 4.6.1
Directx11

(all checked)
The error is: That the Editor is uploaded in Ram but won't start. no error message, nothing, it remain in ram consuming 28-30mb but won't start.
i have installed correctly all prerequisites.
i'm using the binary release.
Please Help i really want to use this engine seems amazing! D:

**Comment by KLNHOMEALONE** [comment]
Either c++ redistributable 2015 is not correctly installed or your antivir software prevents it from running. Ypu're gonna need to add xenko in exclusions list

**Comment by RealAquilus** [comment]
i have re-installed windows and now work, thanks anyway!
