### ISSUE TITLE
Set Mesh.BoundingBox broken in 1.8.3 beta

### ISSUE THREAD

**Issue by LyingDwarf** [SiliconStudio/xenko#468]
Mesh.BoundingBox property setter previously worked but now throws MissingMethodException in 1.8.3 beta.
Additionally, dynamic shadows are no longer cast by such meshes. This may likely be due to the lack of a bounding box being assigned. Bounding sphere can still be assigned.

**Comment by jwollen** [comment]
Hi!

Does this happen for meshes you created in the Game Studio, or from code? 
If it's from code, could you try rebuilding your whole project? We changed Mesh.BoundingBox from a property to a field, breaking binary compatibility.

**Comment by LyingDwarf** [comment]
It was from code generating the meshes at run time, and you are absolutely correct, it was binary incompatibility. My code is housed in a separate library that was still referencing an older version of the Xenko dlls than the launcher project. Thank you for alerting me to that issue.
