### ISSUE TITLE
Scene viewport rendering incorrectly on Surface Pro 3

### ISSUE THREAD

**Issue by AvengerDr** [SiliconStudio/xenko#470]
I was trying Xenko on my SP3. However, as you can see from the image below, the scene viewport is displayed incorrectly.

<img width="1080" alt="capture" src="https://cloud.githubusercontent.com/assets/4924830/19614036/ea92a5f6-97e8-11e6-9fe8-3d073cb6482e.PNG">

**Comment by manu-silicon** [comment]
This is a known issue (see #464). Which OS version are you using on the Surface Pro 3?

**Comment by AvengerDr** [comment]
Oh sorry about that. I am using Windows 10.
Afterwards, I noticed that problem on my main desktop PC. I think it's because on the SP3 the zoom level was set at 150%. Some game or multiple screen setting must have (temporarily) set altered that on my desktop PC too.

I have also noted another problem, but I am not sure if it has already been reported. It's about shaders, I tried to search the open issues but I haven't found any reference. Basically if a shader is supposed to return a color, and it is not returned, the mesh disappears but I can see some polygons flashing in and out. In some more severe cases the editor goes in full seizure mode and starts flashing on and off very rapidly. If this has not been reported yet I'm happy to open a new issue.

**Comment by manu-silicon** [comment]
Just to be sure, is this the anniversary update?

**Comment by 0xFireball** [comment]
I noticed this too: Anniversary update, Surface Pro 4

This is my screen:

![image](https://cloud.githubusercontent.com/assets/15932100/19703402/8b02265c-9ab8-11e6-9c56-491f82c3a6d6.png)

**Comment by manu-silicon** [comment]
Note that if you open Explorer where you installed Xenko, look for the folder `GamePackages\Xenko.1.8.3-beta\Bin\Windows-Direct3D11` (replace 1.8.3 with your version of Xenko installed), thrn open the Windows properties of `Xenko.GameStudio.exe`. Make sure to check `Disable display scaling on high DPI settings`.

Then relaunch Xenko. It should be fine with the downside that the UI elements would appear quite small.

**Comment by 0xFireball** [comment]
Thanks for the workaround. Will this be fixed in the next release?
