### ISSUE TITLE
Xenko 1.9 build error - MaterialSurfaceNormalMap

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#489]
Hi,
trying to update to Xenko 1.9, but got lots of these errors on build:

[C:/Program Files/Silicon Studio/Xenko/GamePackages/Xenko.1.9.0-beta/Assets/Shared/Materials/Shaders/MaterialSurfaceNormalMap.xksl(8,5)]: Error:  E3008: The class [MaterialSurfaceNormalMap] could not be instanciated because the number of required generic does not match the number of passed generics.
Error: BuildStep EffectCompile [XenkoForwardShadingEffect] failed.

Any idea what's wrong?

**Comment by jwollen** [comment]
Thanks for the report!

We changed the `MaterialSurfaceNormalMap` shader (it now has one more generic parameter).

That shader may be part of your `.xkeffectlog` file, but it is supposed to be automatically upgraded when converting to 1.9. If you have an effect log, can you post the contents? To solve the issue, you can delete the effect log, or, if you want to keep it, replace all
```
-   ClassName: MaterialSurfaceNormalMap
    GenericArguments: [false, true]
```
with
```
-   ClassName: MaterialSurfaceNormalMap
    GenericArguments: [false, true, true]
```

If that doesn't help, could you try to create some sample (e.g. MaterialSample) with version 1.8 and open it with 1.9, and check if you have the same issue?

Thanks!

**Comment by EmptyKeys** [comment]
I see. Think i find the issue. I had to upgrade project more than one time (coz of errors in my code) and each upgrade added "true" to the list of arguments. I don't keep effect log in source control (should I? ). Deleting log fixed it. :)
