### ISSUE TITLE
Ray casting does not work against a 2D Box

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#494]
Raycast does not hit box colliders with `Is2D` set to true. i.e.

With a box at (0,0,0) with size of (1,1,1) and `Is2D` set to true. Doing a raycast from (-10,0,0) to (10,0,0) should get a hit.

It seems to work for other 2D colliders, i.e. sphere , capsule etc.

**Comment by sinkingsugar** [comment]
Thanks for the report. Will investigate soon.

**Comment by sinkingsugar** [comment]
Should be fixed in the next release from now.
