### ISSUE TITLE
[Improvement] AssetCompiler behavior with missing Assemblies in .NET Standard Assemblies

### ISSUE THREAD

**Issue by jason-wilmans** [SiliconStudio/xenko#498]
Xenko Version: 1.9.1-beta

When the AssetCompiler tries to build assets in an assembly that misses one or more of the needed NuGet .NET Standard libraries such as System.Runtime.Extensions, it hangs for a long time. (In my case multiple tens of minutes), The error message then provided is not indicative of the user's error. The problems would be easier to fix, if the AssetCompiler would print the underlying exceptions that most probably report missing assemblies.

**Comment by xen2** [comment]
Do you still have the issue with a newly created project using 1.10?

**Comment by jason-wilmans** [comment]
I got my program up and running with .NET Standard with a lot of pain when I initially posted that issue. Once got over that issue it runs pretty smoothly now.. 

I will try to reproduce it again and see if it has gotten better with the new version. Might need a few days to get around to it. Stay tuned..

**Comment by bobo-branden** [comment]
No I was not able to reproduce the issue. Thank you for the quick resonse.
