### ISSUE TITLE
Failure when creating a project

### ISSUE THREAD

**Issue by DaZombieKiller** [SiliconStudio/xenko#499]
I installed Xenko last night, with the intention of trying out the engine (binary release 1.9.1-beta), and whenever I attempt to create a project I am met with a series of errors at the "Creating session..." window.  
The errors seem to stem from the Xenko assemblies not being located, with the primary error being:  

    Error: The type or namespace name 'SiliconStudio' could not be found (are you missing a using directive or an assembly reference?)

Other errors that I receive are related to this one, such as Xenko-related classes not existing.  
The full error log (from when creating a project based on the FirstPersonShooter template) can be found here: https://gist.github.com/DaZombieKiller/8b33616bc91377e16607e016fd1ab422

**Comment by DaZombieKiller** [comment]
Update: completely reinstalling Xenko does not solve the issue

**Comment by Kryptos-FR** [comment]
Hello. Sorry for the inconvenience.

Could you provide us some more details about your machine specs?
* CPU x86/x64, vendor
* operating system
* versions of .Net installed (look in Control Panel)
* versions of MSBuild installed (look in Control Panel)

Just in case, do you have an anti-virus software actively monitoring your system?

**Comment by DaZombieKiller** [comment]
I have since completely reset my Windows install, and Xenko now works, so unfortunately any major details about the issue I provide will be from memory.

CPU: x64, Intel Core i7
OS: Windows 10 Pro x64
.NET: All versions from 3.0 upwards, from memory
MSBuild: 14.0 & 15.0

There was an anti-virus enabled, however disabling it made no difference. (Trend Micro Internet Security)
