### ISSUE TITLE
Asset View Doesn't Reopen

### ISSUE THREAD

**Issue by kevinarthurackerman** [SiliconStudio/xenko#508]
I accidentally closed the asset view, and now when I go to re-enable it, it indicates that it is open but does not add the menu to the editor. I tried closing and re-enabling the asset view in another project and it did work there - this is practically a brand new project so I am not sure what would be different.

![screenshot](https://cloud.githubusercontent.com/assets/22435096/21468086/d8ba007e-c9c8-11e6-9641-d28243b2bfc7.png)

**Comment by Benlitz** [comment]
Hi,

Sorry for your trouble, this issue may happen occasionally and we'll fix it as soon as possible.
Meanwhile, you can reset the layout of the Game Studio using Edit > Settings, then go into the Interface section and look for the Reset layout button.
If it doesn't work you can still try to delete C:\Users\[your.account]\AppData\Roaming\Silicon Studio\Xenko\GameStudioInternal.conf

**Comment by Benlitz** [comment]
Note: we just fixed this issue today (it happened to several users and was getting quite annoying), so it should not happen anymore starting from the next release (1.9.3, to be released probably beginning of January)

**Comment by kevinarthurackerman** [comment]
Thank you for the fast response, both with the work around and with the solution.
