### ISSUE TITLE
In the "Curve" editor are "curves" actually curves?

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#510]
Hi,

When I think of curves I think of quadratic/cubic bezier curves. But the editor only shows control points and the lines between them. So I am wondering if the animation is just a linear interpolation between consecutive points or it actual does some sort of quadratic/cubic  interpolation?  

If it is a quadratic/cubic curve it would be nice if the actually curve was shown.

I tried looking through the documentation and could not seem to see anything that explains what I am  asking about.  If I missed something please point me in the right direction.

Cheers,
dfkeenan

**Comment by LautrecOfCarim** [comment]
Hi,

You haven't missed anything, there is only linear interpolation for now. Technically most curve editors support linear, cubic or other kind of interpolation between key poses, but regardless they are usually called curve editors. We only implement linear interpolation for now as we haven't had high demand for this feature yet.

On the other hand the animation system (for character animation) doesn't use the curve editor yet and imports animation assets directly, defaulting to cubic interpolation. We haven't linked the two yet and we might change the implementation a little in the future to make them work together.

Please let me know if you have some issues or requests for the feature.

**Comment by dfkeenan** [comment]
Thanks for the reply. As long as this info get's explained in the documentation at some point I think it should be fine. Although cubic curves etc. would be appreciated. 😄 

I have only used the curve editor in particles, I can't remember if it is usable anywhere else.  If the proposed "Storyboard" feature (on trello) is going to use curves then I think being able to use higher order curves would be great. Especially if we can use them to animate UI elements. But I would also be happy with baked-in easing functions. But I could always roll my own :thinking:
