### ISSUE TITLE
[Question] What is the purpose of <userdoc/> tags?

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#517]
Hi,

I was wondering what the purpose of the userdoc tags in the Xenko code are for.  Are they what drives the info at the bottom of the property/inspector window? 

![userdoc](https://cloud.githubusercontent.com/assets/6070165/22392565/76b8489c-e546-11e6-81f7-407eb9197a20.png)

Cause some are these are wrong/missing and I get tempted to point it out or perhaps fix it myself.

**Comment by Kryptos-FR** [comment]
You guessed it right. The `<userdoc>` tags are used to generate the documentation that is visible in the property grid. We try to keep them accurate but it is possible that there are some errors.
You can fix them and open a pull request if needed.

**Comment by xen2** [comment]
FYI, Graphics Compositor is going through a quite heavy rewrite/refactor, so you probably don't want to improve those right now.

**Comment by dfkeenan** [comment]
Ok. I was going to ask elsewhere what sort of ETA to expect for documentation of composition and, customizing materials/shaders. But I guess that, that would be on hold till the re-write is done?
