### ISSUE TITLE
"No scripts inheriting from ScriptComponent found in asset ..."

### ISSUE THREAD

**Issue by Xerexus** [SiliconStudio/xenko#518]
Upon the creation of my default project, I created a script derived from SyncScript. When attempting to add it to any entity via the drag and drop interface via the entity's property panel, it gave me the error 'No scripts inheriting from ScriptComponent found in asset MyFirstXenko.Game/BackAndForth'.

I'm following this outdated tutorial: https://www.youtube.com/watch?v=nJWBMzphSno

![image](https://cloud.githubusercontent.com/assets/17334038/22401517/4c3ba426-e62a-11e6-987e-3f5342f7af4f.png)

Whilst the issue has been resolved via restarting Xenko Engine, I do believe that this should be looked into.

**Comment by Kryptos-FR** [comment]
After you create a script or modify an existing one, you need to reload the assemblies so that the Game Studio can show the changes.
See http://doc.xenko.com/latest/manual/get-started/create-a-script.html

**Comment by Xerexus** [comment]
I see. Thank-you!
