### ISSUE TITLE
SetScissorRectangles for Direct3D12 and Vulkan

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#521]
Hi, would be possible to implement CommandList class method SetScissorRectangles for Direct3D12 and Vulkan please? It's just few lines of code tho. Without that I can't use them.

I would do it myself, but I don't have Visual Studio 2013 to compile Xenko and test it.

Thanks

**Comment by xen2** [comment]
Sure, we will look into it!

**Comment by xen2** [comment]
SetScissorRectangles is available on all platforms with 1.10

**Comment by EmptyKeys** [comment]
perfect, thanks :)
