### ISSUE TITLE
Can't Add Script Components

### ISSUE THREAD

**Issue by RandomAnimeGamer** [SiliconStudio/xenko#524]
Is there any reason why Script Component Class Names would suddenly disappear from the Add Component menu?
![can t add scripts](https://cloud.githubusercontent.com/assets/21181824/22694631/33e66410-ed05-11e6-9ee8-ceeaf6d18893.png)

**Comment by Kryptos-FR** [comment]
Did you make sure the scripts compile correctly and that the assemblies were reloaded?

**Comment by RandomAnimeGamer** [comment]
That's actually a really good question, I just realized this when re-opening my project. 
![image](https://cloud.githubusercontent.com/assets/21181824/22695644/aae6df92-ed08-11e6-90d3-8165868a6467.png)

**Comment by RandomAnimeGamer** [comment]
Yep, I had to fix some code bugs that came up after my partner added a script. This fixed the problem.
