### ISSUE TITLE
FindVisualChildrenOfType<TextBlock>() cannot be casted in array or list

### ISSUE THREAD

**Issue by Maxdg95** [SiliconStudio/xenko#525]
Hey Xenko,

recently switched from Unity to Xenko but im running against this error(which I tackled though).

If you try to add all children of an UIComponent directly to an array.

`List<TextBlock> textBlock = uiComponent?.Page?.RootElement?.FindVisualChildrenOfType<TextBlock>() ` & `TextBlock[] textblock = uiComponent?.Page?.RootElement?.FindVisualChildrenOfType<TextBlock>()`

They both result in the "Cannot implicitly convert type" error.

However if I foreach the FindVisualChildrenOfType and add them to a list through that it does work.

Not sure if this is intended. Came from unity so suspected that would be a thing that worked

**Comment by Kryptos-FR** [comment]
The return type of `FindVisualChildrenOfType<T>` is `IEnumerable<T>` as can be seen in the [documentation](http://doc.xenko.com/latest/api/SiliconStudio.Xenko.UI.VisualTreeHelper.html#SiliconStudio_Xenko_UI_VisualTreeHelper_FindVisualChildrenOfType__1_SiliconStudio_Xenko_UI_UIElement_).

If you want a list or an array you can use one of the following Linq extension:
```
List<TextBlock> textBlockList = RootElement.FindVisualChildrenOfType<TextBlock>().ToList();
TextBlock[] textBlockArray = RootElement.FindVisualChildrenOfType<TextBlock>().ToArray();
```
