### ISSUE TITLE
[Samples] TopDownRPG - Highlight LootBox does not work.

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#544]
Hi,

The Highlight LootBox functionality seems to be broken. It can be fixed without code changes.  The code is expecting the `ModelComponent` to have `Materials` and it "doesn't".

I fixed it by checking the 2 materials:

![image](https://cloud.githubusercontent.com/assets/6070165/23336697/d898b914-fc22-11e6-88a1-08a7c3fc44e4.png)

Cheers,
dfkeenan

**Comment by LautrecOfCarim** [comment]
Hi @dfkeenan 

I like fixes without code changes :) 

What is actually happening is that the script expects the materials to be overridden (this is what the checkbox is for), but they are not. So in runtime the list of override materials is empty. To be really robust, you can use the list of materials on the model asset instead, which is guaranteed not to be empty (in PlayerInput.cs):
```
var materialCount = modelComponentB.Model.Materials.Count;
```

I fixed it internally, thanks for the report!

**Comment by dfkeenan** [comment]
😄  You're welcome

I thought of changing the code to use the models materials as well. But I didn't dig to hard after overriding the materials worked. And I thought it might have been done that way for "reasons".
