### ISSUE TITLE
[Game Studio] Asset preview sometimes renders outside of Game Studio window.

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#545]
Like the title says the asset preview opens outside the window. It goes back to the correct spot if you activate the "Asset preview" tab. Guessing GS doesn't know where to place the HwndHost when the tab it is supposed to be in isn't active.

image removed (probably too late)

**Comment by xen2** [comment]
We solved a bunch of similar issues recently.
Hopefully you won't have the issue with next releases.
