### ISSUE TITLE
Mouse disappears while adjusting color sliders ImageElement

### ISSUE THREAD

**Issue by Maxdg95** [SiliconStudio/xenko#546]
Mouse disappears and is only visible inside the Editor Render window, but no longer visible inside the inspector windows.

This happens when the UIPage tab is undocked from main screen and specifically after dragging the Green slider(Could be lucky hit)

Also if you manage to click the color picker after the mouse disappears the mouse is totally gone in any window unless you unfocus and close the color picker window.

**Comment by Maxdg95** [comment]
Btw. I've managed to record the behaviour after the bug occurred, so you can see what happens after.

https://www.youtube.com/watch?v=KIsnIuEEGP0

**Comment by Kryptos-FR** [comment]
Thanks for the report.
There was an issue in text field (in property grid) when using the dragging functionalities with another mouse button than the left one. This has been fixed internally.

**Comment by Maxdg95** [comment]
Kryptos,

I wasn't dragging with another button than the left one. didn't even know it was possible to drag with another mouse button besides left one.

**Comment by Kryptos-FR** [comment]
This could happen for other reason too, but using another button triggers it every time.
Anyway this should be fixed in next release. I will close this issue once the version is released. If it still happens for you (with new version), feel free to reopen it.

**Comment by Maxdg95** [comment]
I can confirm this is fixed in 1.10, tried my best to see if I could break it but no way it is breaking.
