### ISSUE TITLE
[Documentation] Improve documentation about custom UI Libraries

### ISSUE THREAD

**Issue by Maxdg95** [SiliconStudio/xenko#550]
Currently I'm struggling to create my own variants of ToggleButtons and creating custom libraries, although the custom libraries are implemented in GameStudio I can't find a way to actually implement them inside my UIPage.

**Comment by Kryptos-FR** [comment]
Hello. Thanks for your feedback and sorry to hear you have issues with the UI libraries.

To be able to use an element created in a library it must have a name. Make sure that the `Name` property of the top elements is not empty.

PS: issues with Xenko documentation should be created in the [xenko-docs](https://github.com/SiliconStudio/xenko-docs/issues) repository.
