### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by horizonindie** [SiliconStudio/xenko#564]
Hi everyone, i'm porting my development to Xenko from Unity. (Sorry for my bad english)
Basically i developed a car: Axis y for rotation, axis Z for forward movement.
In unity is working fine but not in Xenko: eulers angles not modify the axis orientation ( if i rotate my car (y) the other x,z, axis not rotate with it).
Also, the quaternion rotation ( that i don't understand yet) won't work because ( i don't know why) reduce the y scale of the car while are rotating.
Somebody know the mistakes?

**Comment by Kryptos-FR** [comment]
Hello. Thank you for your interest in Xenko.

Issuesc reated here on GitHub are supposed to be relate to the engine itself (i.e. bugs or suggestions). Here it seems that you are looking for help on how to use the engine. I invite you to reach the community in either the [forums](https://forums.xenko.com/) or the [Gitter chat](https://gitter.im/SiliconStudio/xenko). I also encourage you to read our documentation. We have recently updated it to get new users started.
