### ISSUE TITLE
Xenko crashing on project startup

### ISSUE THREAD

**Issue by RandomAnimeGamer** [SiliconStudio/xenko#566]
![crashed when loading project](https://cloud.githubusercontent.com/assets/21181824/25068859/0dee6118-2225-11e7-9915-148bc1eba79a.png)
The image explains it all. I made some edits to my project and Xenko refused to build it because the "server didn't provide a meaningful response"
Windows Problem Reporter actually showed that the server program just outright crashed upon starting the compilation, which is why the above problem happened.

Now, every time I open my project, Xenko just crashes. Why would this happen? Is there any way to fix this?
Even closing down Xenko and making sure it doesn't run in the background didn't stop it from crashing. Sent a bunch of crash reports.

I'm using Xenko 1.10 on Windows 10 (64-bit) with an i7-4500U and 8GB RAM.

**Comment by RandomAnimeGamer** [comment]
Here's the crash report:
`Application: GameStudio
UserEmail: jwbrauns@asu.edu
UserMessage: 
XenkoVersion: 1.10.2-beta
GameStudioVersion: 4
ThreadName: 
CurrentDirectory: C:\Program Files\Silicon Studio\Xenko
CommandArgs: C:\_Rapporter-Xenko3D\RapporterV2\RapporterV2.sln
OsVersion: Microsoft Windows 10 Home 10.0.14393 x64
ProcessorCount: 4
Exception: NullReferenceException: Object reference not set to an instance of an object.
   at SiliconStudio.Xenko.Engine.Events.EventReceiverBase`1.Finalize() in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Engine\Engine\Events\EventReceiverBase.cs:line 123

GPU0.AdapterCompatibility: Intel Corporation
GPU0.AdapterDACType: Internal
GPU0.AdapterRAM: 1073741824
GPU0.Availability: 3
GPU0.Caption: Intel(R) HD Graphics Family
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1366
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 60
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 768
GPU0.Description: Intel(R) HD Graphics Family
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20161110000000.000000-000
GPU0.DriverVersion: 20.19.15.4549
GPU0.InfFilename: oem101.inf
GPU0.InfSection: iHSWM_w10
GPU0.InstalledDisplayDrivers: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll,igdumdim32,igd10iumd32,igd10iumd32,igd12umd32
GPU0.MaxRefreshRate: 60
GPU0.MinRefreshRate: 60
GPU0.Monochrome: False
GPU0.Name: Intel(R) HD Graphics Family
GPU0.PNPDeviceID: PCI\VEN_8086&DEV_0A16&SUBSYS_131D1043&REV_09\3&11583659&0&10
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: LOLNARUTOGAMERS
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1366 x 768 x 4294967296 colors
GPU0.VideoProcessor: Intel(R) HD Graphics Family
Log: `

**Comment by RandomAnimeGamer** [comment]
I found out that a specific line of code causes the issue. The problem here is that I don't understand why it's causing an issue. Here's what I posted on the Xenko Answers forums:

So I found out why this happened, apparently an event receiver in one of my Async scripts causes it. The problem is, I'm not sure why it happens. Here's the code:

    using System; using System.Collections.Generic; using System.Linq; using System.Text; using System.Threading.Tasks;
    using SiliconStudio.Core.Mathematics; using SiliconStudio.Xenko.Input;
    using SiliconStudio.Xenko.Engine; using SiliconStudio.Xenko.Engine.Events; using SiliconStudio.Xenko.Physics;
    
    namespace RapporterV2.Quest { public class SwordQ : AsyncScript {
        public static readonly EventKey<bool> main = new EventKey<bool>();
        public static readonly EventReceiver<bool> sword = new EventReceiver<bool>(QuestManager.swordQuest);
        public override async Task Execute() {
            var trigger = Entity.Get<PhysicsComponent>();
            trigger.ProcessCollisions = true;
            while(Game.IsRunning) {
                var firstCollision = await trigger.NewCollision();//wait for entities coming in
                var isQ = false; q.TryReceive(out isQ); if(isQ) main.Broadcast(true);
                var collision = await trigger.CollisionEnded();
                main.Broadcast(false);
            }
        }
    } }

Whenever I comment out the EventReceiver on line 7, the project loads fine. Why would this happen?
This is the specific line Xenko takes issue with:

    public static readonly EventReceiver<bool> sword = new EventReceiver<bool>(QuestManager.swordQuest);

This is the event key in QuestManager under the same namespace as this script:

    public static readonly EventKey<bool> swordQuest = new EventKey<bool>();

**Comment by xen2** [comment]
This should be fixed in 2.0.
Please reopen if you still have the issue.
