### ISSUE TITLE
Launcher - Visual Studio Plugin (Installer) not supporting/recognizing VS2017

### ISSUE THREAD

**Issue by VenHayz** [SiliconStudio/xenko#570]
**The Visual Studio plugin installer only recognizes Visual Studio versions: 2013, 2014, and 2015.** This needs to be updated. If this is simply because VS2017 is not supported, then we need to work towards supporting it. NOTE: With experience, lots of 2017 directories have changed. It will, unfortunately, be much like a wild goose chase.
![image](https://cloud.githubusercontent.com/assets/13669835/25317631/1b52b41e-2831-11e7-9c52-8fd633a8110c.png)
Thanks

**Comment by xen2** [comment]
Visual Studio plugin will soon be released with VS2017 support.

**Comment by manu-silicon** [comment]
It is now available. Checkout Xenko v2.0.
