### ISSUE TITLE
Bug: Entity missing Group property

### ISSUE THREAD

**Issue by Zulusas** [SiliconStudio/xenko#573]
Hi, i installed new Xenko version (2.0.0.2).  
Entity class missing Group property.

public SiliconStudio.Xenko.Engine.EntityGroup Group { get; set; } //missing

**Comment by xenux** [comment]
Hi @Zulusas this API has disappeared with new Scene management system introduced in Xenko 2.0. We updated the API reference (ctrl+f5 might be needed) sorry for the inconvenience. 
http://doc.xenko.com/latest/api/index.html

**Comment by Zulusas** [comment]
Hi, how can i set Render Group for Entity in code? It can be done with 
EntityManager 
<http://doc.xenko.com/latest/api/SiliconStudio.Xenko.Engine.Entity.html#SiliconStudio_Xenko_Engine_Entity_EntityManager>? 
Can you provide some sample code? It would be nice to have some 
documentation/video about new Scene management system.
