### ISSUE TITLE
Application fails to launch due to NuGet configuration file repositoryPath setting.

### ISSUE THREAD

**Issue by josh-endries** [SiliconStudio/xenko#576]
I just tried to install this, and while it seemed to work, launching the application (the "Start 2.0.0.2" button) failed. The problem seemed to be that I have a `nuget.config` file in my `C:\` folder which specifies a repository path. It appears that a few Xenko-related packages _did_ get installed into my path, but the application wouldn't launch. Renaming this file and reinstalling worked, however that isn't a long-term solution. Renaming the file back to `nuget.config` re-broke it. When I try to launch it, I get this error:

> Unexpected installation. Cannot find a proper NuGet configuration for [Xenko] in [C:/packages/Xenko.2.0.0.2]

This is my `C:\nuget.config` file:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <config>
        <add key="repositoryPath" value="c:\packages" />
      </config>
    </configuration>

**Comment by manu-silicon** [comment]
Thanks for the report. This issue should be fixed shortly. In the meantime, you can use your workaround, or copy the file `store.config` from the default installation directory `C:\Program Files\Silicon Studio\Xenko` to `C:\packages\Xenko.2.0.0.2\`.

**Comment by manu-st** [comment]
Although this is fixed internally, it will only work when a new version of the Launcher (i.e. version > 1.7.0) will be available.
