### ISSUE TITLE
iOS build error with Visual Studio 2017

### ISSUE THREAD

**Issue by jonstelly** [SiliconStudio/xenko#577]
These checks in Xenko.iOS.targets are failing when only Visual Studio 2017 is installed:

```
  <Target Name="EnsureXamarinVersion" BeforeTargets="PrepareForBuild">
    <Error Condition="'$(XamarinVersion)' == ''" Text="Xamarin iOS version was not found. Ensure HKEY_LOCAL_MACHINE\SOFTWARE\Xamarin\iOS\InstalledVersion is properly set."/>
    <Error Condition="($(XamarinIOSMajorVersion) == 8 And $(XamarinIOSMinorVersion) &lt; 10) Or $(XamarinIOSMajorVersion) &lt; 8" Text="Xamarin iOS version less than 8.10 is not compatible with Xenko. Please upgrade to 8.10."/>
  </Target>
```

I have the Xamarin and iOS components installed correctly, but in Visual Studio 2017 they no longer register themselves in that registry key that the targets file is looking for.  If I comment out those two lines then my iOS project builds and runs correctly.

**Comment by sinkingsugar** [comment]
I removed this check, it is not necessary anyway.
