### ISSUE TITLE
Case conversion issue breaks editor/templates and auto generated shaders

### ISSUE THREAD

**Issue by quadraxas** [SiliconStudio/xenko#578]
The editor fails to load files under 
`C:\Program Files\Silicon Studio\Xenko\GamePackages\Xenko.2.0.0.2\Assets\Shared\Images`
directory on a computer that uses **Turkish** locale with the following error:

`System.ArgumentException: The directory name c:\program files\silicon studio\xenko\gamepackages\xenko.2.0.0.2\assets\shared\ımages\luminanceeffect is invalid.`

I noticed all characters in the error message is lower-case. Lowercase **I** in Turkish is not **i** but **ı**, so _Images_ becomes _ımages_ insted of _**i**mages_.

Windows does not work that way in directory names though, it works like it does in english systems.

Renaming folder from _Images_ to _images_ with lowercase **i** fixes the issue. But of course this is a temporary fix. This issue might cause other problems that i did not encounter yet.

Editor should not use system locale when converting paths to lowercase.

**Comment by quadraxas** [comment]
Same issue breaks auto-generated shaders. Check line 113 of this gist:  https://gist.github.com/quadraxas/7ad9d598da6394ee293c39c473d3a04c

uppercase **i** in Turkish is **İ**, which breaks the shader compiler with `Unexpected character` error.
You need to pass additional(probably en-us) CultureInfo to toUpper and toLower methods.

**Comment by Kryptos-FR** [comment]
Thanks for the report. We will investigate those casing issues.

**Comment by Kryptos-FR** [comment]
We identified areas where we were using the user locale instead of an invariant (English) one. This fix will be in the next release. Feel free to reopen if you still have similar issues.
