### ISSUE TITLE
repeated install failure 

### ISSUE THREAD

**Issue by azaineldin** [SiliconStudio/xenko#580]
hi xenko,
first time.. launcher started.. failed to start download ..
second, third,... fourth times...  download game studio failed at 99%....

still trying...

**Comment by Kryptos-FR** [comment]
Hello.
Sorry for the inconvenience. Could you give us more details on your machine setup? For example:
* OS version
* Your country and if your internet connection is behind a proxy
* Any antivirus or firewall installed on your system that might impact the installation
* Any other information that might be relevant

**Comment by azaineldin** [comment]
hi,
thank you for your prompt reply... much appreciated..

I finally succeeded to install xenko, but unfortunately not the visual
studio plugins.. same thing.. never complete the download..

I have windows 8.1
I live in Cairo- Egypt.
I use ESET Smart Security 9.0 (AntiVirus/Firewall). but never had any
problems before on installations.

I attached the failure log file for your attention.. hope this will help..

will keep trying and inform you of any progress..

thank you..

Dr. Ahmad Hosny, RPh, PharmD.

**Comment by manu-st** [comment]
Could you attached the failure log via the github web interface? Looks like attachements are removed when replying via email.

**Comment by azaineldin** [comment]
failure log : this log was created when I tried to create my first run of the program after the installation, 
I am sorry I did not find any log for the download failure..
changing the file format from .rtf to .pdf removed all the formatting and font colors that distinguish the failure entries from the normal entries.. I hope that wont be a problem for you..
[xenko Document.pdf](https://github.com/SiliconStudio/xenko/files/965623/xenko.Document.pdf)

**Comment by azaineldin** [comment]
dear sir,

your update 2.0 solved all my problems... Thank you..

I also suspected a problem with my visual studio installation, so I
uninstalled it and reinstalled it with ALL options just to be sure...

running like a charm...

Thank you for your prompt response and wish you all the best...

Dr. Ahmad Hosny...
