### ISSUE TITLE
When going to desktop from full screen, game is displayed in bordeless window.

### ISSUE THREAD

**Issue by wanton7** [SiliconStudio/xenko#68]
Hi I'm using 1.0.0-beta02 and tried SpriteEntity Sample and added this line "GraphicsDeviceManager.IsFullScreen = true;" to constructor.

After I do ctrl+shift+esc to open task manager game is displayed on borderless window and doesn't go back to full screen.

My desktop resolution is 1920x1080 if that helps.

**Comment by sinkingsugar** [comment]
Should be fixed now.
