### ISSUE TITLE
Windows Phone project fails to deploy to device

### ISSUE THREAD

**Issue by gitfool** [SiliconStudio/xenko#73]
I failed to deploy the JumpyJet sample to a Nokia Lumia 520 with the following error:

> 2>------ Deploy started: Project: JumpyJet.WindowsPhone, Configuration: Release WindowsPhone-ARM ------
2>Error : DEP6810 : MdilXapCompile.exe failed with error code 2001. See log file 'D:\Users\Sean\Documents\Paradox Projects\JumpyJet\JumpyJet\JumpyJet.WindowsPhone\obj\WindowsPhone-ARM\Release\MDIL\MDILXapCompileLog.txt' for more details.

The log file has the following error at the end:

> CrossGen failed
Error processing assembly D:\Users\Sean\Documents\Paradox Projects\JumpyJet\JumpyJet\JumpyJet.WindowsPhone\obj\WindowsPhone-ARM\Release\MSIL\SiliconStudio.Core.dll
Raw error code: 2148733978

[MDILXapCompileLog.txt.zip | uploaded via ZenHub](https://files.zenhub.io/5452002f27262a4766dfb940)

**Comment by xen2** [comment]
Closing, we had apps passing certs on Win10 UWP so everything should be fine now.

**Comment by artemious7** [comment]
Thanks, @Gavin-Williams. Renaming this folder worked for me.

> C:\Users\Gavin\AppData\Local\Microsoft\Phone Tools\CoreCon\12.0\
